"use strict";

const {
  StageThreeBatchExecutionProfile,
} = require("./stage_three_batch_execution_profile");

const BATCH_007_EXECUTION_PROFILE = new StageThreeBatchExecutionProfile({
  schemaVersion: 1,
  batchId: "stage-3.candidate-007-fishing-bb8b3939",
  batchNumber: "007",
  executionStageLabel: "Stage 3.7.1",
  auditStageLabel: "Stage 3.7.0",
  focusedStageId: "stage-3.7.2",
  prebuildStageId: "stage-3.7.3",
  sourceReleaseVersion: "0.24.43",
  targetReleaseVersion: "0.24.44",
  auditPath: "architecture/migration/stage_3_batch_007_audit.json",
  executionPlanPath: "architecture/migration/stage_3_batch_007_execution_plan.json",
  testMatrixPath: "architecture/migration/stage_3_batch_007_test_matrix.json",
  expectedTargetCount: 6,
  expectedExportCount: 6,
  expectedActivationCount: 6,
  expectedConsumerCount: 9,
  expectedDependencyEdgeCount: 0,
  expectedTargets: [
    { currentPath: "src/core/fishing/line_constrained_fish_motion_resolver.js", targetPath: "src/game/domain/fishing/line_constrained_fish_motion_resolver.js", exports: ["LineConstrainedFishMotionResolver"] },
    { currentPath: "src/core/fishing/line_radial_movement_splitter.js", targetPath: "src/game/domain/fishing/line_radial_movement_splitter.js", exports: ["LineRadialMovementSplitter"] },
    { currentPath: "src/core/fishing/reel_retrieve_speed_calculator.js", targetPath: "src/game/domain/fishing/reel_retrieve_speed_calculator.js", exports: ["ReelRetrieveSpeedCalculator"] },
    { currentPath: "src/core/fishing/rod_pull_state.js", targetPath: "src/game/domain/fishing/rod_pull_state.js", exports: ["RodPullState"] },
    { currentPath: "src/core/fishing/rod_stroke_state.js", targetPath: "src/game/domain/fishing/rod_stroke_state.js", exports: ["RodStrokeState"] },
    { currentPath: "src/core/fishing/simple_fight_force_calculator.js", targetPath: "src/game/domain/fishing/simple_fight_force_calculator.js", exports: ["SimpleFightForceCalculator"] },
  ],
  expectedActivationIds: [
    "activation-00287f399f05",
    "activation-a63204f0676b",
    "activation-ccddea60d16c",
    "activation-da8d3f6d370f",
    "activation-dcb3cecb345c",
    "activation-f5eefdd6e6e2",
  ],
  expectedActivationPositions: [91, 92, 112, 131, 132, 139],
  expectedBridgeIds: [
    "bridge-1975df3eebf9",
    "bridge-292102f00c09",
    "bridge-9987d14a6b96",
    "bridge-c5b20a842e06",
    "bridge-d88e995bce27",
    "bridge-dcceaaf04a57",
    "bridge-dd65f33afb4a",
    "bridge-ddf61a64424b",
    "bridge-f20190e70bbd",
  ],
  expectedTopology: {
    beforeProjectModuleCount: 25,
    afterProjectModuleCount: 31,
    beforeActivationCount: 26,
    afterActivationCount: 32,
    beforeBridgeCount: 48,
    afterBridgeCount: 57,
  },
  includeRuntimeActiveState: true,
  persistActiveBatchPhase: false,
  includeDetailedStatePerformanceGates: true,
  behaviorPhases: ["classic-baseline", "temporary-esm-parity", "post-cutover-esm"],
  compatibilityPhases: ["pre-build-fixture", "temporary-esm-parity", "post-build-runtime"],
  scmCheckpointRequired: true,
  sourceReleaseTag: "v0.24.43",
  bridgeReason: "Preserve the exact synchronous Fishing State and Motion Primitives consumer set until its approved migration stage removes the legacy symbols.",
  rollbackRule: "restore-only-batch-007-delta-and-keep-batches-001-through-006",
  consumerSetSource: "stage-3.7.1-planned-canonical-bridge-records",
  operationIds: [
    "verify-frozen-evidence",
    "open-batch-007",
    "create-six-named-esm-targets",
    "render-six-activation-shims",
    "register-nine-consumer-bridges",
    "project-preliminary-manifest-metadata",
    "build-single-cumulative-runtime",
    "validate-identity-timing-and-behavior",
    "persist-and-reconcile-observations",
    "run-full-acceptance",
    "close-release-0.24.44",
  ],
}).value;

module.exports = { BATCH_007_EXECUTION_PROFILE };
