"use strict";

const {
  StageThreeBatchExecutionProfile,
} = require("./stage_three_batch_execution_profile");

const BATCH_006_EXECUTION_PROFILE = new StageThreeBatchExecutionProfile({
  schemaVersion: 1,
  batchId: "stage-3.candidate-006-fishing-e48e70d8",
  batchNumber: "006",
  executionStageLabel: "Stage 3.6.2",
  auditStageLabel: "Stage 3.6.1",
  focusedStageId: "stage-3.6.3",
  prebuildStageId: "stage-3.6.4",
  sourceReleaseVersion: "0.24.42",
  targetReleaseVersion: "0.24.43",
  auditPath: "architecture/migration/stage_3_batch_006_audit.json",
  executionPlanPath: "architecture/migration/stage_3_batch_006_execution_plan.json",
  testMatrixPath: "architecture/migration/stage_3_batch_006_test_matrix.json",
  expectedTargetCount: 6,
  expectedExportCount: 6,
  expectedActivationCount: 6,
  expectedConsumerCount: 7,
  expectedDependencyEdgeCount: 0,
  expectedTargets: [
    { currentPath: "src/core/fishing/hold_opposition_resolver.js", targetPath: "src/game/domain/fishing/hold_opposition_resolver.js", exports: ["HoldOppositionResolver"] },
    { currentPath: "src/core/fishing/landing_lift_tension_calculator.js", targetPath: "src/game/domain/fishing/landing_lift_tension_calculator.js", exports: ["LandingLiftTensionCalculator"] },
    { currentPath: "src/core/fishing/line_constraint_state_resolver.js", targetPath: "src/game/domain/fishing/line_constraint_state_resolver.js", exports: ["LineConstraintStateResolver"] },
    { currentPath: "src/core/fishing/pole_fight_sector_geometry.js", targetPath: "src/game/domain/fishing/pole_fight_sector_geometry.js", exports: ["PoleFightSectorGeometry"] },
    { currentPath: "src/core/fishing/rod_control_tension_mode_resolver.js", targetPath: "src/game/domain/fishing/rod_control_tension_mode_resolver.js", exports: ["RodControlTensionModeResolver"] },
    { currentPath: "src/core/float_tackle_line_budget_policy.js", targetPath: "src/game/domain/fishing/float_tackle_line_budget_policy.js", exports: ["FloatTackleLineBudgetPolicy"] },
  ],
  expectedActivationIds: [
    "activation-7678742c83cf",
    "activation-775fb46bb6ce",
    "activation-8f8220d288e5",
    "activation-9857928fc9d0",
    "activation-f70148ad6a58",
    "activation-ffea5244c4bf",
  ],
  expectedActivationPositions: [88, 123, 126, 130, 134, 140],
  expectedBridgeIds: [
    "bridge-225041916b22",
    "bridge-451e340bf590",
    "bridge-6c073ecab1b3",
    "bridge-87740b3c6660",
    "bridge-c6c1e5eb790e",
    "bridge-c7d38bfb778f",
    "bridge-f6d56e05e037",
  ],
  expectedTopology: {
    beforeProjectModuleCount: 19,
    afterProjectModuleCount: 25,
    beforeActivationCount: 20,
    afterActivationCount: 26,
    beforeBridgeCount: 41,
    afterBridgeCount: 48,
  },
  includeRuntimeActiveState: false,
  persistActiveBatchPhase: false,
  includeDetailedStatePerformanceGates: false,
  behaviorPhases: ["classic-baseline", "post-cutover-esm"],
  compatibilityPhases: ["pre-build-fixture", "post-build-runtime"],
  scmCheckpointRequired: false,
  sourceReleaseTag: null,
  bridgeReason: "Preserve the exact synchronous Fishing Domain Primitives II consumer set until its approved migration stage removes the legacy symbols.",
  rollbackRule: "restore-only-batch-006-delta-and-keep-batches-001-through-005",
  consumerSetSource: "stage-3.6.2-planned-canonical-bridge-records",
  operationIds: [
    "verify-frozen-evidence",
    "open-batch-006",
    "create-six-named-esm-targets",
    "render-six-activation-shims",
    "register-seven-consumer-bridges",
    "project-preliminary-manifest-metadata",
    "build-single-cumulative-runtime",
    "validate-identity-timing-and-behavior",
    "persist-and-reconcile-observations",
    "run-full-acceptance",
    "close-release-0.24.43",
  ],
}).value;

module.exports = { BATCH_006_EXECUTION_PROFILE };
