"use strict";

const { StageThreeBatchExecutionProfile } = require("./stage_three_batch_execution_profile");
const { StageThreeBatchPreflightProfile } = require("./stage_three_batch_preflight_profile");

const allocation = (objectExpressions, arrayExpressions, newExpressions, objectFreezeCalls,
  objectAssignCalls = 0, roundingCalls = 0) => ({ objectExpressions, arrayExpressions,
  newExpressions, objectFreezeCalls, objectAssignCalls, roundingCalls });
const fishing = "src/core/fishing/";
const domain = "src/game/domain/fishing/";
const target = (suffix, exports) => ({ currentPath: fishing + suffix,
  targetPath: domain + suffix, exports });
const BATCH_013_EXECUTION_PROFILE = new StageThreeBatchExecutionProfile({
  schemaVersion: 1,
  batchId: "stage-3.candidate-013-fishing-0267b3ea",
  batchNumber: "013",
  executionStageLabel: "Stage 3.13.1",
  auditStageLabel: "Stage 3.13.0",
  focusedStageId: "stage-3.13.2",
  prebuildStageId: "stage-3.13.3",
  sourceReleaseVersion: "0.24.49",
  targetReleaseVersion: "0.24.50",
  auditPath: "architecture/migration/stage_3_batch_013_audit.json",
  executionPlanPath: "architecture/migration/stage_3_batch_013_execution_plan.json",
  testMatrixPath: "architecture/migration/stage_3_batch_013_test_matrix.json",
  expectedTargetCount: 6,
  expectedExportCount: 8,
  expectedActivationCount: 8,
  expectedConsumerCount: 7,
  expectedDependencyEdgeCount: 0,
  expectedTargets: [
    target("fish_direction_intent_sampler.js", ["DEFAULT_FISH_LATERAL_RANGE",
      "DEFAULT_FISH_RADIAL_RANGE", "FishDirectionIntentSampler"]),
    target("fishing_cast_exposure_resolver.js", ["FishingCastExposureResolver"]),
    target("player_force_budget_allocator.js", ["PlayerForceBudgetAllocator"]),
    target("player_pressure/player_pressure_fatigue_calculator.js", ["PlayerPressureFatigueCalculator"]),
    target("rod_control_angle_resolver.js", ["RodControlAngleResolver"]),
    target("stamina/stamina_regen_calculator.js", ["StaminaRegenCalculator"]),
  ],
  expectedActivationIds: ["activation-18af7e975cb0", "activation-2a74f4c05932",
    "activation-3890808eb3cc", "activation-3ed53946507b", "activation-79ef4d67c996",
    "activation-a44add7fda39", "activation-bafccd351254", "activation-dca4cdb154de"],
  expectedActivationPositions: [67, 95, 101, 107, 124, 124, 124, 127],
  expectedBridgeIds: ["bridge-2943aa6fa8b8", "bridge-509dd42a0477", "bridge-68a669b68de3",
    "bridge-9420d12f86ac", "bridge-9f6a7d891df3", "bridge-a2b17a1794bf",
    "bridge-d1647c1fa147"],
  expectedTopology: { beforeProjectModuleCount: 44, afterProjectModuleCount: 50,
    beforeActivationCount: 45, afterActivationCount: 53,
    beforeBridgeCount: 76, afterBridgeCount: 83 },
  includeRuntimeActiveState: true,
  persistActiveBatchPhase: true,
  includeDetailedStatePerformanceGates: true,
  behaviorPhases: ["classic-baseline", "temporary-esm-parity", "post-cutover-esm"],
  compatibilityPhases: ["pre-build-fixture", "temporary-esm-parity", "post-build-runtime"],
  scmCheckpointRequired: true,
  sourceReleaseTag: "v0.24.49",
  bridgeReason: "Preserve the exact Fishing domain consumers until their legacy symbols are removed.",
  rollbackRule: "restore-only-batch-013-delta-and-keep-batches-001-through-012",
  consumerSetSource: "stage-3.13.0-live-observation-and-frozen-consumer-set",
  operationIds: ["verify-frozen-evidence", "open-batch-013", "create-six-named-esm-targets",
    "render-eight-candidate-activation-shims", "project-seven-consumer-bridges",
    "project-candidate-manifest", "validate-candidate-and-commit-atomic-cutover",
    "validate-identity-timing-state-and-behavior", "persist-and-reconcile-observations",
    "run-full-acceptance", "close-release-0.24.50"],
}).value;

const BATCH_013_PREFLIGHT_PROFILE = new StageThreeBatchPreflightProfile({
  schemaVersion: 1,
  stageLabel: "Stage 3.13.0",
  artifactKind: "cyber-fishing-stage-3-batch-preflight-audit",
  batchId: BATCH_013_EXECUTION_PROFILE.batchId,
  sourceReleaseVersion: BATCH_013_EXECUTION_PROFILE.sourceReleaseVersion,
  executionProfile: BATCH_013_EXECUTION_PROFILE,
  sideEffectEvidence: { path: "architecture/migration/stage_3_batch_013_side_effect_review.json",
    sha256: "59f3ac8e0128d5b2567e53aa97b66a9d0ef07bb03e4677026df2110fd15a1ec6" },
  reviewedContracts: {
    [fishing + "fish_direction_intent_sampler.js"]: {
      classification: "authoritative-owner", instanceFields: ["#rng"], publicStateShape: [],
      resultShape: ["radial", "lateral"], stableResultIdentity: false,
      mutatesCallerInputs: false, semanticRisk: "frozen-range-identity-rng-order-and-three-symbol-activation",
      performanceClassification: "existing-fish-direction-sampling", hotLoopCallSites: ["src/entities/fish.js"],
      callSiteEvidence: [{ path: "src/entities/fish.js", marker: "new FishDirectionIntentSampler(this.#rng)" }],
      allocationBaseline: allocation(3, 2, 0, 1),
      frozenConstants: { className: "FishDirectionIntentSampler", bindings: {
        DEFAULT_FISH_RADIAL_RANGE: { location: "1:35", values: [0.35, 1] },
        DEFAULT_FISH_LATERAL_RANGE: { location: "2:36", values: [-1, 1] },
      } },
    },
    [fishing + "fishing_cast_exposure_resolver.js"]: {
      classification: "stateless", instanceFields: [], publicStateShape: [], resultShape: [],
      stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "cast-exposure-formula-and-single-global-exposure",
      performanceClassification: "existing-cast-transition-calculation", hotLoopCallSites: [],
      callSiteEvidence: [{ path: "src/app/application.js", marker: "new FishingCastExposureResolver()" },
        { path: "src/app/states.js", marker: "new FishingCastExposureResolver()" }],
      allocationBaseline: allocation(1, 0, 0, 0),
      legacyExposure: { symbol: "FishingCastExposureResolver", location: "13:1" },
    },
    [fishing + "player_force_budget_allocator.js"]: {
      classification: "authoritative-owner", instanceFields: [], publicStateShape: [], resultShape: [],
      stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "force-allocation-formulas-clamps-and-window-exposure",
      performanceClassification: "existing-fight-physics-budget-allocation",
      hotLoopCallSites: ["src/systems/fight_physics_system.js"],
      callSiteEvidence: [{ path: "src/systems/fight_physics_system.js", marker: "new PlayerForceBudgetAllocator()" }],
      allocationBaseline: allocation(13, 0, 0, 1),
      legacyExposure: { symbol: "PlayerForceBudgetAllocator", location: "199:3", mechanism: "window-property" },
    },
    [fishing + "player_pressure/player_pressure_fatigue_calculator.js"]: {
      classification: "authoritative-owner", instanceFields: [], publicStateShape: [], resultShape: [],
      stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "pressure-fatigue-rounding-clamps-and-window-exposure",
      performanceClassification: "existing-fight-physics-pressure-calculation",
      hotLoopCallSites: ["src/systems/fight_physics_system.js"],
      callSiteEvidence: [{ path: "src/systems/fight_physics_system.js", marker: "new PlayerPressureFatigueCalculator()" }],
      allocationBaseline: allocation(24, 0, 0, 3, 0, 1),
      legacyExposure: { symbol: "PlayerPressureFatigueCalculator", location: "439:3", mechanism: "window-property" },
    },
    [fishing + "rod_control_angle_resolver.js"]: {
      classification: "authoritative-owner", instanceFields: [], publicStateShape: [], resultShape: [],
      stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "rod-angle-resolution-and-window-exposure",
      performanceClassification: "existing-rod-lateral-angle-resolution",
      hotLoopCallSites: ["src/systems/rod_lateral_control_system.js"],
      callSiteEvidence: [{ path: "src/systems/rod_lateral_control_system.js", marker: "new RodControlAngleResolver()" }],
      allocationBaseline: allocation(3, 0, 0, 1),
      legacyExposure: { symbol: "RodControlAngleResolver", location: "55:3", mechanism: "window-property" },
    },
    [fishing + "stamina/stamina_regen_calculator.js"]: {
      classification: "authoritative-owner", instanceFields: [], publicStateShape: [], resultShape: [],
      stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "stamina-phase-regeneration-and-window-exposure",
      performanceClassification: "existing-stamina-regeneration",
      hotLoopCallSites: ["src/core/fishing/stamina/stamina_phase_machine.js"],
      callSiteEvidence: [{ path: "src/core/fishing/stamina/stamina_phase_machine.js",
        marker: "new StaminaRegenCalculator()" }],
      allocationBaseline: allocation(13, 0, 0, 7),
      legacyExposure: { symbol: "StaminaRegenCalculator", location: "131:3", mechanism: "window-property" },
    },
  },
  migrationGates: ["six-exact-source-and-method-shapes", "eight-export-identities-and-activations",
    "two-frozen-literal-range-evaluation-effects", "five-reviewed-class-exposures",
    "seven-exact-consumer-relationships", "all-legacy-activation-positions-preserved",
    "zero-config-platform-browser-dev-dependencies", "zero-added-hot-loop-allocations"],
}).value;

module.exports = { BATCH_013_PREFLIGHT_PROFILE, BATCH_013_EXECUTION_PROFILE };
