"use strict";

const { StageThreeBatchExecutionProfile } = require("./stage_three_batch_execution_profile");
const { StageThreeBatchPreflightProfile } = require("./stage_three_batch_preflight_profile");

const allocation = (objectExpressions, arrayExpressions, newExpressions, objectFreezeCalls,
  objectAssignCalls = 0, roundingCalls = 0) => ({ objectExpressions, arrayExpressions,
  newExpressions, objectFreezeCalls, objectAssignCalls, roundingCalls });
const fishing = "src/core/fishing/";
const domain = "src/game/domain/fishing/";
const target = (suffix, exports) => ({ currentPath: fishing + suffix,
  targetPath: domain + suffix, exports });
const fightPhysics = "src/systems/fight_physics_system.js";
const phaseMachine = "src/core/fishing/stamina/stamina_phase_machine.js";
const tackleStress = "src/systems/tackle_stress_system.js";
const windowExposure = (symbol, location) => ({ symbol, location, mechanism: "window-property" });

const BATCH_014_EXECUTION_PROFILE = new StageThreeBatchExecutionProfile({
  schemaVersion: 1,
  batchId: "stage-3.candidate-014-fishing-fefd469b",
  batchNumber: "014",
  executionStageLabel: "Stage 3.14.1",
  auditStageLabel: "Stage 3.14.0",
  focusedStageId: "stage-3.14.2",
  prebuildStageId: "stage-3.14.3",
  sourceReleaseVersion: "0.24.50",
  targetReleaseVersion: "0.24.51",
  auditPath: "architecture/migration/stage_3_batch_014_audit.json",
  executionPlanPath: "architecture/migration/stage_3_batch_014_execution_plan.json",
  testMatrixPath: "architecture/migration/stage_3_batch_014_test_matrix.json",
  expectedTargetCount: 6,
  expectedExportCount: 6,
  expectedActivationCount: 6,
  expectedConsumerCount: 6,
  expectedDependencyEdgeCount: 0,
  expectedTargets: [
    target("landing_lift_readiness_policy.js", ["LandingLiftReadinessPolicy"]),
    target("player_pressure/player_pressure_fatigue_state.js", ["PlayerPressureFatigueState"]),
    target("player_pressure/player_tension_build_rate_resolver.js", ["PlayerTensionBuildRateResolver"]),
    target("stamina/stamina_drain_calculator.js", ["StaminaDrainCalculator"]),
    target("stamina/stamina_transition_resolver.js", ["StaminaTransitionResolver"]),
    target("tackle_failure_selector.js", ["TackleFailureSelector"]),
  ],
  expectedActivationIds: ["activation-0621e81b56b8", "activation-2eff98891b2d",
    "activation-8110687cd3e1", "activation-9398dc78c283", "activation-aff068f84afe",
    "activation-ee66782e3f9e"],
  expectedActivationPositions: [97, 100, 106, 108, 137, 141],
  expectedBridgeIds: ["bridge-550eed84bb7c", "bridge-9b112859f6f0", "bridge-a59383ea4b2f",
    "bridge-a880353d8927", "bridge-c53a729057bb", "bridge-ebcf2ae98878"],
  expectedTopology: { beforeProjectModuleCount: 50, afterProjectModuleCount: 56,
    beforeActivationCount: 53, afterActivationCount: 59,
    beforeBridgeCount: 83, afterBridgeCount: 89 },
  includeRuntimeActiveState: true,
  persistActiveBatchPhase: true,
  includeDetailedStatePerformanceGates: true,
  behaviorPhases: ["classic-baseline", "temporary-esm-parity", "post-cutover-esm"],
  compatibilityPhases: ["pre-build-fixture", "temporary-esm-parity", "post-build-runtime"],
  scmCheckpointRequired: true,
  sourceReleaseTag: "v0.24.50",
  bridgeReason: "Preserve the exact Fishing domain consumers until their legacy symbols are removed.",
  rollbackRule: "restore-only-batch-014-delta-and-keep-batches-001-through-013",
  consumerSetSource: "stage-3.14.0-live-observation-and-frozen-consumer-set",
  operationIds: ["verify-frozen-evidence", "open-batch-014", "create-six-named-esm-targets",
    "render-six-candidate-activation-shims", "project-six-consumer-bridges",
    "project-candidate-manifest", "validate-candidate-and-commit-atomic-cutover",
    "validate-identity-timing-state-and-behavior", "persist-and-reconcile-observations",
    "run-full-acceptance", "close-release-0.24.51"],
}).value;

const BATCH_014_PREFLIGHT_PROFILE = new StageThreeBatchPreflightProfile({
  schemaVersion: 1,
  stageLabel: "Stage 3.14.0",
  artifactKind: "cyber-fishing-stage-3-batch-preflight-audit",
  batchId: BATCH_014_EXECUTION_PROFILE.batchId,
  sourceReleaseVersion: BATCH_014_EXECUTION_PROFILE.sourceReleaseVersion,
  executionProfile: BATCH_014_EXECUTION_PROFILE,
  sideEffectEvidence: { path: "architecture/migration/stage_3_batch_014_side_effect_review.json",
    sha256: "889837de05b33d2729926474eb18c9cc82a3ee127b49922054c0c962858e8b17" },
  reviewedContracts: {
    [fishing + "landing_lift_readiness_policy.js"]: {
      classification: "authoritative-owner", instanceFields: [], publicStateShape: [],
      resultShape: [], stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "landing-lift-readiness-reasons-epsilon-and-window-exposure",
      performanceClassification: "existing-landing-lift-readiness-evaluation",
      hotLoopCallSites: [fightPhysics],
      callSiteEvidence: [{ path: fightPhysics, marker: "new LandingLiftReadinessPolicy()" }],
      allocationBaseline: allocation(11, 0, 0, 1),
      legacyExposure: windowExposure("LandingLiftReadinessPolicy", "136:3"),
    },
    [fishing + "player_pressure/player_pressure_fatigue_state.js"]: {
      classification: "authoritative-owner",
      instanceFields: ["controlBreakEnabled", "controlBreakFatigueProgressThreshold",
        "controlBreakMinContinuousPressureMs", "delayAfterPressureMs", "efficiency", "enabled",
        "fatigueDurationMs", "fatigueElapsedMs", "fatigueProgress", "fatigueRatio",
        "fatigueRemainingMs", "graceDurationMs", "graceElapsedMs", "graceRemainingMs",
        "holdElapsedMs", "isControlExhausted", "pressureActive", "pressureHoldMs", "pressureKg",
        "recoveryDelayElapsedMs", "recoveryDelayMs", "recoveryDelayRemainingMs", "recoveryIdleMs",
        "recoveryPerSecond", "recoveryProgress", "recoveryRemainingMs", "recoveryState",
        "sourceActive", "sourceMode", "sourceReason", "stateName"],
      publicStateShape: [], resultShape: [], stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "mutable-fatigue-state-owner-defaults-reset-frame-and-window-exposure",
      performanceClassification: "existing-fight-physics-fatigue-state-frame",
      hotLoopCallSites: [fightPhysics],
      callSiteEvidence: [{ path: fightPhysics, marker: "new PlayerPressureFatigueState()" }],
      allocationBaseline: allocation(2, 0, 0, 1),
      legacyExposure: windowExposure("PlayerPressureFatigueState", "175:3"),
    },
    [fishing + "player_pressure/player_tension_build_rate_resolver.js"]: {
      classification: "authoritative-owner", instanceFields: ["#config"], publicStateShape: [],
      resultShape: [], stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "tension-build-rate-thresholds-multipliers-and-window-exposure",
      performanceClassification: "existing-fight-physics-tension-build-rate",
      hotLoopCallSites: [fightPhysics],
      callSiteEvidence: [{ path: fightPhysics, marker: "new PlayerTensionBuildRateResolver()" }],
      allocationBaseline: allocation(10, 0, 0, 2),
      legacyExposure: windowExposure("PlayerTensionBuildRateResolver", "114:3"),
    },
    [fishing + "stamina/stamina_drain_calculator.js"]: {
      classification: "authoritative-owner", instanceFields: [], publicStateShape: [],
      resultShape: [], stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "stamina-drain-advantage-curve-and-window-exposure",
      performanceClassification: "existing-stamina-drain-calculation",
      hotLoopCallSites: [phaseMachine],
      callSiteEvidence: [{ path: phaseMachine, marker: "drainCalculator = new StaminaDrainCalculator()" }],
      allocationBaseline: allocation(4, 0, 0, 1),
      legacyExposure: windowExposure("StaminaDrainCalculator", "88:3"),
    },
    [fishing + "stamina/stamina_transition_resolver.js"]: {
      classification: "authoritative-owner", instanceFields: [], publicStateShape: [],
      resultShape: [], stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "stamina-exhaustion-phase-transitions-and-window-exposure",
      performanceClassification: "existing-stamina-phase-transition",
      hotLoopCallSites: [phaseMachine],
      callSiteEvidence: [{ path: phaseMachine,
        marker: "transitionResolver = new StaminaTransitionResolver()" }],
      allocationBaseline: allocation(8, 0, 0, 4),
      legacyExposure: windowExposure("StaminaTransitionResolver", "88:3"),
    },
    [fishing + "tackle_failure_selector.js"]: {
      classification: "authoritative-owner",
      instanceFields: ["DEFAULT_TIE_BREAK_PRIORITY", "RESULT_BY_COMPONENT"],
      publicStateShape: [], resultShape: [], stableResultIdentity: false, mutatesCallerInputs: false,
      semanticRisk: "failure-order-tie-break-static-frozen-tables-and-class-identity",
      performanceClassification: "existing-tackle-failure-selection",
      hotLoopCallSites: [tackleStress],
      callSiteEvidence: [{ path: tackleStress, marker: "new TackleFailureSelector()" }],
      allocationBaseline: allocation(9, 3, 2, 2),
      frozenStaticFields: { className: "TackleFailureSelector", bindings: {
        DEFAULT_TIE_BREAK_PRIORITY: { location: "2:39",
          values: ["leader", "line", "hook", "rod", "reel"] },
        RESULT_BY_COMPONENT: { location: "9:32", values: { leader: "leader_lost",
          line: "line_break", hook: "hook_bent", rod: "rod_broken", reel: "reel_broken" } },
      } },
    },
  },
  migrationGates: ["six-exact-source-and-method-shapes", "six-export-identities-and-activations",
    "two-frozen-static-literal-evaluation-effects", "five-reviewed-window-class-exposures",
    "six-exact-consumer-relationships", "all-legacy-activation-positions-preserved",
    "zero-config-platform-browser-dev-dependencies", "zero-added-hot-loop-allocations"],
}).value;

module.exports = { BATCH_014_PREFLIGHT_PROFILE, BATCH_014_EXECUTION_PROFILE };
