class ArchitectureDocumentRenderer {
  render(policy) {
    return [
      "# CyberFishing Module Architecture",
      "",
      "> Generated from `architecture/module_architecture.json`. Do not edit this file manually.",
      "> Change the policy and run `npm run architecture:docs`.",
      "",
      "This is the authoritative human-readable view of the executable module policy. Anything not explicitly allowed by the dependency tables is forbidden.",
      "",
      "## Target boundaries",
      "",
      this.#renderBoundaryTable(policy),
      "",
      "Boundary resolution uses the longest matching path prefix. Physical directories are created only when a real migration batch moves code into them.",
      "",
      "## Qualified dependency rules",
      "",
      this.#renderQualifiedDependencies(policy),
      "",
      "### Configuration and domain",
      "",
      this.#renderConfigurationRules(policy),
      "",
      "## Production and development graphs",
      "",
      this.#renderEnvironments(policy),
      "",
      "## Module roles",
      "",
      this.#renderModuleRoles(policy),
      "",
      "Module roles are recorded in the migration manifest. They let architecture checks enforce qualified edges without relying on filename guesses.",
      "",
      "## Migration statuses",
      "",
      this.#renderStatuses(policy),
      "",
      "## Migration waves",
      "",
      this.#renderWaves(policy),
      "",
      "## Migration manifest",
      "",
      this.#renderMigrationManifest(policy),
      "",
      "## Architecture guards",
      "",
      this.#renderArchitectureGuards(policy),
      "",
      "## ESM conventions",
      "",
      this.#renderModuleConventions(policy),
      "",
      "## Dependency injection",
      "",
      this.#renderDependencyInjection(policy),
      "",
      "## Exceptions",
      "",
      this.#renderExceptions(policy),
      "",
      "## Change workflow",
      "",
      "1. Define the current module, target boundary, dependencies, consumers, globals, blockers, role, and migration wave.",
      "2. Migrate one dependency cluster together with its focused tests and manifest update.",
      "3. Run architecture checks, focused checks, and the full regression suite.",
      "4. Do not update a baseline or add an exception merely to make a check green.",
      "5. Keep gameplay changes outside architecture migration tasks.",
      "",
    ].join("\n");
  }

  #renderBoundaryTable(policy) {
    const rows = policy.boundaries.map((boundary) => [
      boundary.id,
      boundary.pathPrefixes.join("<br>"),
      boundary.allowedDependencies.length > 0
        ? boundary.allowedDependencies.join(", ")
        : "None",
      boundary.description,
    ]);
    return this.#table(
      ["Boundary", "Path prefixes", "Allowed dependencies", "Responsibility"],
      rows,
    );
  }

  #renderQualifiedDependencies(policy) {
    if (policy.qualifiedDependencies.length === 0) {
      return "No qualified dependency rules are registered.";
    }
    return this.#table(
      ["Rule", "Edge", "Allowed target roles", "Reason"],
      policy.qualifiedDependencies.map((rule) => [
        rule.id,
        `${rule.sourceBoundary} → ${rule.targetBoundary}`,
        rule.allowedTargetModuleRoles.join(", "),
        rule.description,
      ]),
    );
  }

  #renderConfigurationRules(policy) {
    const rawBoundary = policy.getBoundary("game-config-raw");
    const qualifier = policy.qualifiedDependencies.find(
      (rule) =>
        rule.sourceBoundary === "game-config" &&
        rule.targetBoundary === "game-domain",
    );
    const delivery = policy.definition.dependencyInjection
      .domainConfigurationDelivery;
    return [
      "- `game-domain` cannot import `game-config` or `game-config-raw`.",
      `- \`game-config-raw\` has ${rawBoundary.allowedDependencies.length} allowed dependencies and therefore remains dependency-free.`,
      `- \`game-config → game-domain\` is limited to target roles: ${qualifier.allowedTargetModuleRoles.map((role) => `\`${role}\``).join(", ")}.`,
      `- Configuration reaches domain through: ${delivery.map((mode) => `\`${mode}\``).join(", ")}.`,
      "- Domain concepts must be modeled as domain contracts/value objects, not disguised as raw configuration constants.",
    ].join("\n");
  }

  #renderEnvironments(policy) {
    const production = policy.definition.environments.production;
    const development = policy.definition.environments.development;
    return [
      `- Production root: \`${production.rootBoundary}\`.`,
      `- Production must not reach: ${production.forbiddenReachableBoundaries.map((id) => `\`${id}\``).join(", ")}.`,
      `- Development root: \`${development.rootBoundary}\`; its graph must reach \`dev\`.`,
      "- Production layers never depend on development layers. Development may consume public production boundaries.",
    ].join("\n");
  }

  #renderModuleRoles(policy) {
    return this.#table(
      ["Role", "Meaning"],
      policy.moduleRoles.map((role) => [role.id, role.description]),
    );
  }

  #renderStatuses(policy) {
    return this.#table(
      ["Status", "Allowed next statuses", "Meaning"],
      policy.statuses.map((status) => [
        status.id,
        status.allowedTransitions.join(", "),
        status.description,
      ]),
    );
  }

  #renderWaves(policy) {
    return this.#table(
      ["Order", "Wave", "Target boundaries", "Purpose"],
      policy.waves.map((wave) => [
        String(wave.order),
        wave.id,
        wave.targetBoundaries.length > 0
          ? wave.targetBoundaries.join(", ")
          : "Architecture/tooling only",
        wave.description,
      ]),
    );
  }

  #renderMigrationManifest(policy) {
    const manifest = policy.migrationManifest;
    const consistency = manifest.fieldConsistency;
    const observation = policy.observationContract;
    const resolution = observation.resolutionModel;
    const persistence = observation.persistenceModel;
    const integrity = observation.integrityModel;
    const environment = observation.environmentModel;
    const classification = policy.classificationContract;
    const candidates = classification.candidateSelection;
    const schemaMigration = manifest.schemaMigrations.find(
      (migration) => migration.toVersion === manifest.schemaVersion,
    );
    return [
      `- Schema version: \`${manifest.schemaVersion}\`.`,
      `- Controlled schema migration: \`v${schemaMigration.fromVersion} → v${schemaMigration.toVersion}\` (\`${schemaMigration.id}\`).`,
      `- Source scope: \`${manifest.sourceScope}\`; coverage rule: \`${manifest.coveragePolicy}\`.`,
      "- No fixed source-module count is part of policy; the checked invariant is manifest entries equal current filesystem entries.",
      `- Stable entry order: \`${manifest.entrySort}\`.`,
      `- Current area strategy: \`${manifest.currentArea.strategy}\`.`,
      `- Legacy order source: \`${manifest.legacyLoadOrder.source}\`, starting at \`${manifest.legacyLoadOrder.firstValue}\`; files outside the legacy graph use \`null\`.`,
      `- Observation mode: \`${observation.scannerMode}\`; principle: \`${observation.principle}\`; architecture classification: \`${observation.architectureClassification}\`.`,
      `- Observation statuses: ${observation.statuses.map((status) => `\`${status.id}\``).join(", ")}.`,
      `- Provider mechanisms: ${observation.providerModel.mechanisms.map((mechanism) => `\`${mechanism}\``).join(", ")}.`,
      `- Provider availability: ${observation.providerModel.availabilities.map((availability) => `\`${availability}\``).join(", ")}; only ${observation.providerModel.confirmedWithoutControlFlow.map((availability) => `\`${availability}\``).join(", ")} can be confirmed without additional control-flow proof.`,
      `- Consumer access requirements: ${observation.consumerModel.accessRequirements.map((requirement) => `\`${requirement}\``).join(", ")}; execution phases: ${observation.consumerModel.executionPhases.map((phase) => `\`${phase}\``).join(", ")}.`,
      `- Resolution unit: one \`${resolution.resolutionUnit.kind}\` keyed by ${resolution.resolutionUnit.keyFields.map((field) => `\`${field}\``).join(" + ")}; deduplication: \`${resolution.resolutionUnit.deduplication}\`.`,
      `- Provider candidates are grouped by \`${resolution.candidateModel.identity}\`; ambiguity is evaluated between \`${resolution.candidateModel.ambiguityScope}\`, and environment observations are \`${resolution.candidateModel.environmentParticipation}\` from project resolution.`,
      `- Resolution kinds: ${resolution.kinds.map((kind) => `\`${kind}\``).join(", ")}; confirmed edges require exactly ${resolution.confirmedProviderCount} trustworthy provider.`,
      `- Trustworthy provider availability without control-flow proof: ${resolution.availabilityCompatibility.trustworthyProviderAvailabilities.map((availability) => `\`${availability}\``).join(", ")}; guarded access preserves its semantics but does not relax provider proof.`,
      `- Filename/path heuristics: \`${resolution.filenameHeuristics}\`/\`${resolution.pathHeuristics}\`; reverse consumers: \`${resolution.reverseConsumers}\`.`,
      `- \`legacyLoadOrder\` is \`${resolution.legacyLoadOrder.role}\`, never identity or migration priority.`,
      `- Load-order rules: eager → \`${resolution.legacyLoadOrder.executionPhaseRules.eager}\`, conditional → \`${resolution.legacyLoadOrder.executionPhaseRules.conditional}\`, deferred → \`${resolution.legacyLoadOrder.executionPhaseRules.deferred}\`; missing order yields \`${resolution.legacyLoadOrder.missingOrderResult}\`.`,
      `- Self-resolution is \`${resolution.selfResolution.result}\` but its dependency edge is \`${resolution.selfResolution.dependencyEdge}\`; automatic preference is \`${resolution.selfResolution.automaticPreference}\`.`,
      `- Dependency graph lifecycle: \`${resolution.graphModel.lifecycle}\`; edges: \`${resolution.graphModel.edgeCreation}\`; speculative and self edges are \`${resolution.graphModel.speculativeEdges}\`/\`${resolution.graphModel.selfEdges}\`.`,
      `- Transient resolver output contains ${resolution.transientResultModel.sourceFields.map((field) => `\`${field}\``).join(", ")} per source; statuses are ${resolution.transientResultModel.sourceStatuses.map((status) => `\`${status}\``).join(", ")}, and an incomplete provider corpus uses \`${resolution.transientResultModel.providerCorpusIncomplete}\`.`,
      `- Persistence uses \`${persistence.mode}\` via \`${persistence.command}\`, writes \`${persistence.writeTiming}\`, requires \`${persistence.byteStability}\` byte stability, and treats stale source as \`${persistence.staleSourceResult}\`.`,
      `- Fact-level confirmed resolutions persist at \`${persistence.factLevelConfirmed}\`; aggregated inter-file edges persist at \`${persistence.aggregatedInterFileEdges}\`; self-resolution uses \`${persistence.selfResolutionPersistence}\`.`,
      `- Graph authority flows \`${integrity.authoritativeDirection}\`; reverse consumers are \`${integrity.reverseConsumers}\` and persistence is \`${integrity.reversePersistence}\`.`,
      `- Integrity requires \`${integrity.consumerResolutionCardinality}\` outcome per consumer, \`${integrity.edgeProvenance}\` edge provenance, \`${integrity.edgeAggregation}\` aggregation, and \`${integrity.staleObservationCheck}\` freshness.`,
      `- Classic global compatibility is evaluated for \`${resolution.classicScriptCompatibility.environment}\`; global lexical providers resolve identifier consumers only, while var/function/object-backed providers expose global-object access forms.`,
      "- Strictness propagates through program/function directives and enclosing strict scopes; class bodies, methods, field initializers, and static blocks are always strict.",
      `- Symbol classifications: built-ins → \`${environment.symbolClassifications.builtins}\`, browser APIs → \`${environment.symbolClassifications.browserApis}\`, external consumers → \`${environment.symbolClassifications.externalConsumers}\`; architecture classification effect: \`${environment.classificationEffect}\`.`,
      `- Dynamic/unsupported constructs are reported explicitly and produce \`${environment.dynamicConstructResult}\` observation status.`,
      "- Confirmed dependency provenance uses `{ target, symbols, resolution: \"confirmed\" }`; source line numbers are not authoritative manifest data.",
      `- Stage ${classification.stage} classification uses \`${classification.decisionMode}\` decisions; ownership inference is \`${classification.ownershipInference}\` and architecture mutation is \`${classification.architectureMutation}\`.`,
      `- Required classification evidence: ${classification.requiredEvidence.map((source) => `\`${source}\``).join(", ")}; evidence lifecycle: \`${classification.evidenceLifecycle}\`.`,
      `- Forbidden ownership heuristics: ${classification.forbiddenOwnershipHeuristics.map((heuristic) => `\`${heuristic}\``).join(", ")}.`,
      `- Target paths, roles, and blockers are \`${classification.targetPathSelection}\`, \`${classification.roleSelection}\`, and \`${classification.blockerSelection}\`; no candidate rank can populate them.`,
      `- Role compatibility is boundary-owned: ${Object.entries(classification.roleCompatibility).map(([boundary, roles]) => `\`${boundary}\` → ${roles.map((role) => `\`${role}\``).join("/")}`).join("; ")}.`,
      `- Mixed-responsibility modules retain one \`${classification.mixedResponsibility.targetBoundary}\` and blocker \`${classification.mixedResponsibility.blocker}\`.`,
      `- Conservative leaf candidates require \`${candidates.requiredMigrationStatus}\`, \`${candidates.requiredObservationStatus}\` observations, \`${candidates.leafDefinition}\`, and \`${candidates.providerRequirement}\` provider facts; uncertainty policy: \`${candidates.uncertaintyPolicy}\`.`,
      `- Candidate ranking has \`${candidates.classificationEffect}\` classification effect and orders by ${candidates.ordering.map((criterion) => `\`${criterion}\``).join(", ")}.`,
      `- Initial architecture status: \`${manifest.initialArchitecture.migrationStatus}\`; target boundary/path/wave remain \`null\`.`,
      `- Classified statuses requiring a target boundary: ${consistency.classifiedStatusesRequireTargetBoundary.map((status) => `\`${status}\``).join(", ")}.`,
      `- Reviewed statuses requiring target path, role, wave, and reviewed blockers: ${consistency.classifiedStatusesRequireTargetPath.map((status) => `\`${status}\``).join(", ")}.`,
      "- A migration wave must explicitly include the selected target boundary.",
      "- `pending` means not observed; only `verified` with empty result collections means observed and confirmed empty.",
      "- The v1 → v2 migration accepts only pending/empty legacy dependencies, initializes the new language as pending, and creates no dependency edges.",
      "- The v2 → v3 migration accepts only pending/empty provider observations and adds availability semantics without creating provider records.",
      "- The v3 → v4 migration accepts only pending/empty consumer observations and adds access-requirement/execution-phase semantics without creating consumer records.",
      "- The v4 → v5 migration accepts only pending/empty dependency analysis and adds fact-level confirmed resolution provenance without creating edges.",
      "- Reconciliation updates observed facts and preserves reviewed architecture/analysis metadata.",
    ].join("\n");
  }

  #renderModuleConventions(policy) {
    const conventions = policy.definition.moduleConventions;
    return [
      `- Applies to statuses: ${conventions.appliesToStatuses.map((status) => `\`${status}\``).join(", ")}.`,
      `- Preferred exports: \`${conventions.exports.preferredMode}\`; default exports are \`${conventions.exports.defaultExports}\`.`,
      `- Relative imports require the explicit \`${conventions.relativeImports.explicitExtension}\` extension.`,
      `- Barrel modules are \`${conventions.barrelModules}\`.`,
      `- Side-effect imports are \`${conventions.sideEffectImports.policy}\` and limited to: ${conventions.sideEffectImports.allowedBoundaries.map((id) => `\`${id}\``).join(", ")}.`,
      `- Dynamic import targets must be \`${conventions.dynamicImports.target}\`.`,
      `- Runtime global exports policy: \`${conventions.runtimeGlobalExports}\`.`,
      `- Raw config imports: \`${conventions.rawConfiguration.importPolicy}\`; domain concepts as config constants: \`${conventions.rawConfiguration.domainConceptConstants}\`.`,
    ].join("\n");
  }

  #renderArchitectureGuards(policy) {
    const guards = policy.architectureGuards;
    const capabilities = guards.browserCapabilities;
    return [
      `- Unified mechanisms: ${guards.unifiedEdgeMechanisms.map((item) => `\`${item}\``).join(", ")}.`,
      `- Outcomes: ${guards.statuses.map((item) => `\`${item}\``).join(", ")}.`,
      `- Ownership: \`${guards.ownershipValidation}\`; physical path: \`${guards.physicalPathValidation}\`.`,
      `- Cycles: \`${guards.cycleAlgorithm}\`; identity: \`${guards.cycleIdentity}\`.`,
      `- Development-only roles: ${guards.developmentOnlyRoles.map((item) => `\`${item}\``).join(", ")}.`,
      `- Guard artifacts: ${Object.values(guards.artifacts).map((item) => `\`${item}\``).join(", ")}.`,
      `- Browser capabilities: ${Object.keys(capabilities.catalog).map((item) => `\`${item}\``).join(", ")}.`,
      `- Browser capabilities are allowed only in: ${Object.keys(capabilities.allowedBoundaries).map((item) => `\`${item}\``).join(", ")}.`,
      "- Known debt and exceptions match exact canonical identities; stale metadata is a failure.",
      "- Guards are deterministic and read-only: they never change source, policy, manifest, blockers, or registries.",
    ].join("\n");
  }

  #renderDependencyInjection(policy) {
    const dependencyInjection = policy.definition.dependencyInjection;
    return [
      `- Domain configuration delivery: ${dependencyInjection.domainConfigurationDelivery.map((mode) => `\`${mode}\``).join(", ")}.`,
      `- Concrete composition is owned by: ${dependencyInjection.concreteCompositionBoundaries.map((id) => `\`${id}\``).join(", ")}.`,
      `- High-level self-composition: \`${dependencyInjection.highLevelSelfComposition}\`.`,
    ].join("\n");
  }

  #renderExceptions(policy) {
    const exceptions = policy.exceptions;
    const lines = [
      `Required fields: ${exceptions.requiredFields.map((field) => `\`${field}\``).join(", ")}.`,
      "",
      `Allowed rules: ${exceptions.allowedRules.map((rule) => `\`${rule}\``).join(", ")}.`,
      "",
      `Allowed removal stages: ${exceptions.allowedRemovalStages.map((stage) => `\`${stage}\``).join(", ")}.`,
      "",
    ];
    if (exceptions.entries.length === 0) {
      lines.push("Active exceptions: none.");
      return lines.join("\n");
    }
    lines.push(
      this.#table(
        ["ID", "Rule", "Path", "Owner", "Removal stage", "Reason"],
        exceptions.entries.map((entry) => [
          entry.id,
          entry.rule,
          entry.currentPath,
          entry.owner,
          entry.removalStage,
          entry.reason,
        ]),
      ),
    );
    return lines.join("\n");
  }

  #table(headers, rows) {
    const header = `| ${headers.map((value) => this.#escape(value)).join(" | ")} |`;
    const separator = `| ${headers.map(() => "---").join(" | ")} |`;
    const body = rows.map(
      (row) => `| ${row.map((value) => this.#escape(value)).join(" | ")} |`,
    );
    return [header, separator, ...body].join("\n");
  }

  #escape(value) {
    return String(value).replaceAll("|", "\\|").replaceAll("\n", "<br>");
  }
}

module.exports = { ArchitectureDocumentRenderer };
