export const InventoryActionType = Object.freeze({
  OPEN: "inventory/open",
  CLOSE: "inventory/close",
  CATEGORY_SELECT: "inventory/category-select",
  SUBFILTER_TOGGLE: "inventory/subfilter-toggle",
  SORT_CRITERION_SELECT: "inventory/sort-criterion-select",
  SORT_DIRECTION_SELECT: "inventory/sort-direction-select",
  RARITY_FILTER_TOGGLE: "inventory/rarity-filter-toggle",
  INVENTORY_ITEM_ACTIVATE: "inventory/inventory-item-activate",
  INVENTORY_ITEM_LONG_PRESS: "inventory/inventory-item-long-press",
  EQUIPMENT_SLOT_ACTIVATE: "inventory/equipment-slot-activate",
  EQUIPMENT_SLOT_LONG_PRESS: "inventory/equipment-slot-long-press",
  ASSEMBLY_SOCKET_ACTIVATE: "inventory/assembly-socket-activate",
  ASSEMBLY_EQUIP: "inventory/assembly-equip",
  ASSEMBLY_UNEQUIP: "inventory/assembly-unequip",
  ASSEMBLY_DISASSEMBLE: "inventory/assembly-disassemble",
  ASSEMBLY_BACK: "inventory/assembly-back",
  LOADOUT_SAVE: "inventory/loadout-save",
  LOADOUT_PREVIEW_SLOT_EQUIP: "inventory/loadout-preview-slot-equip",
  LOADOUT_EQUIP_ALL: "inventory/loadout-equip-all",
  LOADOUT_DISASSEMBLE: "inventory/loadout-disassemble",
  LOADOUT_PREVIEW_BACK: "inventory/loadout-preview-back",
  AUTO_BAIT_CHANGE: "inventory/auto-bait-change",
  AUTO_CHUM_CHANGE: "inventory/auto-chum-change",
});
