"use strict";

const { StageThreeBatchExecutionProfile } = require("../../../domain_batches/stage_three_batch_execution_profile");
const { StageThreeBatchPreflightProfile } = require("../../../domain_batches/stage_three_batch_preflight_profile");

const allocation = (objectExpressions, arrayExpressions, newExpressions, objectFreezeCalls,
  objectAssignCalls = 0, roundingCalls = 0) => ({ objectExpressions, arrayExpressions,
  newExpressions, objectFreezeCalls, objectAssignCalls, roundingCalls });
const repository = "src/core/inventory/flat_inventory_item_repository.js";
const fish = "src/entities/fish.js";
const tackle = "src/entities/tackle.js";
const buffs = "src/systems/buff_manager.js";
const rodPull = "src/systems/rod_pull_system.js";
const world = "src/world/world.js";
const domain = "src/game/domain/";
const fight = "src/systems/fight_physics_system.js";
const contract = fields => ({ classification: "authoritative-owner", instanceFields: [],
  publicStateShape: [], resultShape: [], stableResultIdentity: false, mutatesCallerInputs: false,
  hotLoopCallSites: [], ...fields });
const imported = (consumer, from, exportName, viaShim, activationId) =>
  ({ consumer, from, exportName, legacySymbol: exportName, viaShim, activationId });

// Batch 050 adopts the Stage 3.50.1 freeze extension (hot-loop equivalence evidence) and migrates six per-frame
// Domain sources: the flat inventory repository (transactional swap of its item Map with rollback and the child
// index rebuilt with it), the fish entity family with its frozen FISH_FIGHT_EVENT table, the tackle entities, the
// buff manager, the rod pull system and the location world. Risk level A: every ESM target is representation-only,
// the live gate re-runs the recorded hot-loop evidence (member fingerprints, allocation sites, game-cycle traces,
// call counts and deltaTime ranges per class) and the game-cycle output is compared before and after the cutover.
// Owner-created collaborators come from reviewed imports (composition identities); nine activations lose their last
// classic readers and retire.
const EXECUTION_PROFILE = new StageThreeBatchExecutionProfile({
  schemaVersion: 1,
  batchId: "stage-3.replan-350.batch-050-fish-fishing-inventory-locations-tackle-5a604f8c",
  batchNumber: "050",
  executionStageLabel: "Stage 3.51.1",
  auditStageLabel: "Stage 3.51.0",
  focusedStageId: "stage-3.51.2",
  prebuildStageId: "stage-3.51.3",
  sourceReleaseVersion: "0.24.87",
  targetReleaseVersion: "0.24.88",
  auditPath: "architecture/migration/stage_3_batch_050_audit.json",
  executionPlanPath: "architecture/migration/stage_3_batch_050_execution_plan.json",
  testMatrixPath: "architecture/migration/stage_3_batch_050_test_matrix.json",
  expectedTargetCount: 6,
  expectedExportCount: 25,
  expectedActivationCount: 12,
  expectedConsumerCount: 12,
  expectedDependencyEdgeCount: 0,
  expectedTargets: [
    { currentPath: repository, targetPath: `${domain}inventory/flat_inventory_item_repository.js`,
      exports: ["FlatInventoryItemRepository"] },
    { currentPath: fish, targetPath: `${domain}fish/fish.js`, exports: ["FISH_FIGHT_EVENT", "Fish", "FishBehavior",
      "FishCondition", "FishEndurancePointsCalculator", "FishPhysicsProfile", "FishStaminaPointsCalculator"] },
    { currentPath: tackle, targetPath: `${domain}tackle/tackle.js`, exports: ["BaitFactory", "Equipment", "FeederEntity",
      "FloatEntity", "Hook", "JigEntity", "Net", "Reel", "Rod", "SpinnerEntity", "WaterEntity", "WobblerEntity"] },
    { currentPath: buffs, targetPath: `${domain}fishing/buff_manager.js`, exports: ["BuffManager"] },
    { currentPath: rodPull, targetPath: `${domain}fishing/rod_pull_system.js`, exports: ["RodPullSystem"] },
    { currentPath: world, targetPath: `${domain}locations/location_world.js`, exports: ["DynamicZone", "GridCell", "LocationMap"] },
  ],
  continuationPlan: { path: "architecture/migration/stage_3_50_review_queue/freeze_extension.json",
    sha256: "484074c63c2ff654561a54e8111452158ec22ed33dccccb1e8c9023ae6f5ffa8" },
  expectedImports: [
    imported(repository, `${domain}inventory/inventory_item_location.js`, "InventoryItemLocation",
      "src/core/inventory/inventory_item_location.js", "activation-c3a8ca11fb0e"),
    imported(fish, `${domain}fishing/fish_direction_intent_sampler.js`, "DEFAULT_FISH_LATERAL_RANGE",
      "src/core/fishing/fish_direction_intent_sampler.js", "activation-3ed53946507b"),
    imported(fish, `${domain}fishing/fish_direction_intent_sampler.js`, "DEFAULT_FISH_RADIAL_RANGE",
      "src/core/fishing/fish_direction_intent_sampler.js", "activation-2a74f4c05932"),
    imported(fish, `${domain}fishing/fish_direction_intent_sampler.js`, "FishDirectionIntentSampler",
      "src/core/fishing/fish_direction_intent_sampler.js", "activation-18af7e975cb0"),
    imported(tackle, "src/engine/math/vector2.js", "Vector2", "src/core/math/vector2.js", "activation-28138de81e82"),
    imported(tackle, `${domain}casting/distance_unit_converter.js`, "DistanceUnitConverter",
      "src/core/distance_unit_converter.js", "activation-27de2804d152"),
    imported(tackle, `${domain}fishing/reel_retrieve_speed_calculator.js`, "ReelRetrieveSpeedCalculator",
      "src/core/fishing/reel_retrieve_speed_calculator.js", "activation-da8d3f6d370f"),
    imported(tackle, `${domain}items/hook/hook_power_policy.js`, "HookPowerPolicy",
      "src/core/items/hook/hook_power_policy.js", "activation-3d418582cb27"),
    imported(tackle, `${domain}items/quality/environmental_compensation_modifier.js`, "EnvironmentalCompensationModifier",
      "src/core/items/quality/environmental_compensation_modifier.js", "activation-6debdbdd2ee1"),
    imported(tackle, `${domain}items/quality/net_quality_modifier.js`, "NetQualityModifier",
      "src/core/items/quality/net_quality_modifier.js", "activation-c4363cf3a576"),
    imported(rodPull, `${domain}fishing/rod_pull_calculator.js`, "RodPullCalculator",
      "src/core/fishing/rod_pull_calculator.js", "activation-552c2d2ba80f"),
    imported(rodPull, `${domain}fishing/rod_pull_state.js`, "RodPullState", "src/core/fishing/rod_pull_state.js",
      "activation-a63204f0676b"),
    imported(rodPull, `${domain}fishing/rod_stroke_state.js`, "RodStrokeState", "src/core/fishing/rod_stroke_state.js",
      "activation-00287f399f05"),
  ],
  expectedActivationIds: ["activation-13045d7d5103", "activation-3a560121fa29", "activation-3c866d430a42",
    "activation-a810d3dd8368", "activation-a8f13a41b355", "activation-a94480a6d930", "activation-d36f5f18f7e5",
    "activation-e72b9af71364", "activation-e7f8998f8ce0", "activation-f31861589962", "activation-f41223b184f9",
    "activation-f4e8bbb8cb91"],
  expectedActivationPositions: [146, 204, 205, 205, 205, 205, 205, 206, 206, 206, 206, 213],
  expectedBridgeIds: ["bridge-1b3a4b1b0495", "bridge-219aa1d24209", "bridge-263392b1d2a3", "bridge-26bcfa4b6eb4",
    "bridge-2b3433dfa33f", "bridge-2fe0c0ead484", "bridge-5d652a225320", "bridge-63a72b4340ed", "bridge-70b087c839cc",
    "bridge-c0fbf6710409", "bridge-c83c8f55a424", "bridge-cd4e72ecdc5e"],
  expectedRetiredActivationIds: ["activation-00287f399f05", "activation-18af7e975cb0", "activation-27de2804d152",
    "activation-2a74f4c05932", "activation-3ed53946507b", "activation-552c2d2ba80f", "activation-6debdbdd2ee1",
    "activation-a63204f0676b", "activation-c4363cf3a576"],
  expectedRetiredBridgeIds: ["bridge-021cb2032053", "bridge-2640efa3c6fa", "bridge-46acc1909f4e", "bridge-53764cfb47d0",
    "bridge-58b9bf61ab47", "bridge-625fc87b2709", "bridge-9f6a7d891df3", "bridge-a45682b300a1", "bridge-d88e995bce27",
    "bridge-dcceaaf04a57", "bridge-f20190e70bbd"],
  informationalDocumentsExcluded: true,
  expectedTopology: { beforeProjectModuleCount: 143, afterProjectModuleCount: 149,
    beforeActivationCount: 133, afterActivationCount: 136,
    beforeBridgeCount: 198, afterBridgeCount: 199 },
  includeRuntimeActiveState: true,
  persistActiveBatchPhase: true,
  includeDetailedStatePerformanceGates: true,
  behaviorPhases: ["classic-baseline", "temporary-esm-parity", "post-cutover-esm"],
  compatibilityPhases: ["pre-build-fixture", "temporary-esm-parity", "post-build-runtime"],
  scmCheckpointRequired: true,
  sourceReleaseTag: "v0.24.87",
  bridgeReason: "Preserve the exact inventory, fish, tackle, rod pull and location consumers until their legacy symbols are removed.",
  rollbackRule: "restore-only-batch-050-delta-and-keep-batches-001-through-049",
  consumerSetSource: "stage-3.50.0-live-observation-and-stage-3.50-frozen-consumer-set",
  operationIds: ["verify-frozen-evidence", "adopt-stage-3.50.1-freeze-extension-and-open-batch-050",
    "create-six-named-esm-targets-with-twenty-five-exports", "render-twelve-candidate-activation-shims",
    "project-twelve-consumer-bridges-and-retire-eleven", "project-candidate-manifest",
    "validate-candidate-and-commit-atomic-cutover", "validate-identity-timing-state-and-behavior",
    "persist-and-reconcile-observations", "run-full-acceptance", "close-release-0.24.88"],
}).value;

const PREFLIGHT_PROFILE = new StageThreeBatchPreflightProfile({
  schemaVersion: 1,
  stageLabel: "Stage 3.51.0",
  artifactKind: "cyber-fishing-stage-3-batch-preflight-audit",
  batchId: EXECUTION_PROFILE.batchId,
  sourceReleaseVersion: EXECUTION_PROFILE.sourceReleaseVersion,
  executionProfile: EXECUTION_PROFILE,
  sideEffectEvidence: { path: "architecture/migration/stage_3_batch_050_side_effect_review.json",
    sha256: "20e7fcf1c7e846f433b95bc835dfd8a26610668d365af6b414ce4f48e7b1d3a5" },
  reviewedContracts: {
    [repository]: contract({
      instanceFields: ["#childrenByParent", "#fallbackSequence", "#instanceIdFactory", "#items", "#now", "#reservationPolicy"],
      publicStateShape: ["size"],
      semanticRisk: "authoritative-inventory-item-map-with-transactional-snapshot-restore-and-rebuilt-child-index",
      performanceClassification: "existing-hot-loop-flat-inventory-item-repository",
      callSiteEvidence: [
        { path: "src/application/inventory/inventory_v2_composition_root.js", marker: "new FlatInventoryItemRepository({" },
        { path: "src/infrastructure/storage/inventory_v2_legacy_migration.js", marker: "new FlatInventoryItemRepository({" },
      ],
      allocationBaseline: allocation(11, 9, 26, 1),
      stateIdentityReview: { className: "FlatInventoryItemRepository", collections: [
        { owner: "FlatInventoryItemRepository#childrenByParent", field: "#childrenByParent", scope: "instance",
          collection: "Map", allowedOperations: ["get", "set"], replacement: "rebuilt-index" },
        { owner: "FlatInventoryItemRepository#items", field: "#items", scope: "instance", collection: "Map",
          allowedOperations: ["delete", "get", "has", "set", "size", "values"], replacement: "transactional-swap" },
      ] },
    }),
    [fish]: contract({
      instanceFields: ["#behavior", "#config", "#currentExhaustion", "#currentLateralIntent", "#currentMove",
        "#currentPull", "#currentRadialIntent", "#currentStamina", "#currentStateName", "#dirTimer",
        "#directionIntentSampler", "#fishConfig", "#hasActiveDebuff", "#holdSpecialStateUntilLeave", "#isLocked",
        "#lastDashBlockedByCatchZone", "#lastDashCheckTimer", "#lastDashDebug", "#lastDebuffName",
        "#lastMovementDebuffDebug", "#level", "#logger", "#logger", "#masteryPowerMult", "#maxEndurance", "#maxStamina",
        "#movementProfile", "#originalBehaviors", "#phase", "#powerDebuff", "#raw", "#rng", "#rng",
        "#runtimeMovementModifier", "#stateTimer", "#targetLateralIntent", "#targetMove", "#targetPull",
        "#targetRadialIntent", "#weight"],
      publicStateShape: ["activeDebuffName", "currentExhaustion", "currentStamina", "hasActiveDebuff", "maxEndurance",
        "maxPoints", "maxStamina", "phase"],
      semanticRisk: "per-frame-fish-behavior-stamina-endurance-and-mastery-with-frozen-fight-event-table",
      performanceClassification: "existing-hot-loop-fish-entity",
      hotLoopCallSites: ["src/systems/fish_force_system.js#calculate"],
      callSiteEvidence: [{ path: "src/app/fishing.js", marker: "new Fish(" },
        { path: "src/app/fishing.js", marker: "new FishCondition(" }],
      allocationBaseline: allocation(57, 10, 6, 3, 1, 4),
      compositionIdentityReview: true,
      frozenConstants: { classNames: ["FishPhysicsProfile", "Fish", "FishBehavior", "FishCondition",
        "FishEndurancePointsCalculator", "FishStaminaPointsCalculator"], bindings: {
        FISH_FIGHT_EVENT: { location: "1:26", values: { CATCH_ZONE_ENTERED: "catch_zone_entered" } },
      } },
    }),
    [tackle]: contract({
      instanceFields: ["#basePower", "#baseRetrieveSpeedMetersPerSec", "#bearingCount",
        "#bearingRetrieveSpeedBonusMetersPerSec", "#castPowerCoefficient", "#compensation", "#config", "#converter",
        "#dragChangeSpeedPerSec", "#dragMaxKg", "#dragMinKg", "#durability", "#durability", "#durability",
        "#durabilityMaxLoadLossPerPercent", "#durabilityMaxLoadLossPerPercent", "#durabilityMaxLoadLossPerPercent",
        "#equipmentPowerLevel", "#hasDrag", "#hasReel", "#holdConfig", "#holdTensionRatio", "#hookPowerGrade",
        "#lengthMeters", "#lineCapacityMeters", "#maxDistance", "#maxLoadKg", "#maxLoadKg", "#maxLoadKg", "#powerPolicy",
        "#qualityGrade", "#qualityModifier", "#retrieveSpeedCalculator", "#variant", "#weight", "_activeBiteSequence",
        "_animDuration", "_animTimer", "_baseColor", "_biteMoveTimer", "_config", "_currentAngle",
        "_currentBiteMoveVelocity", "_currentColor", "_currentHookDepth", "_currentScaleY", "_currentSequenceCount",
        "_debugEvents", "_devFlags", "_environmentalCompensationModifier", "_forceScratch", "_isBiting", "_isGuaranteed",
        "_isHooked", "_isOverDepth", "_isPlayerPullingThisFrame", "_isSinking", "_isSinking", "_lureResistance",
        "_maxDepth", "_motionTiltAngle", "_motionTiltEnabled", "_motionTiltEnabled", "_perspectiveScale", "_position",
        "_pullImpulseAngle", "_pullImpulseScaleY", "_pullImpulseSign", "_rng", "_runtimeConfig", "_sequenceQueue",
        "_sinkingDelayTimer", "_sinkingStartAngle", "_sinkingStartAngle", "_sinkingTimer", "_sinkingTotalTime",
        "_sinkingTotalTime", "_sinkingVisualElapsed", "_startAnimState", "_stepId", "_targetAnimState",
        "_targetHookDepth", "_targetSequenceCount", "_targetWindAngle", "_velocity", "_velocityDamping",
        "_weightedTackleConfig", "_weightedTackleHeightScale", "_windAngleOffset", "_windFluctuationTimer", "_windTimer"],
      publicStateShape: ["isActive", "virtualReach"],
      semanticRisk: "per-frame-float-and-lure-entities-with-rod-reel-hook-net-stats-over-owned-collaborators",
      performanceClassification: "existing-hot-loop-tackle-entities",
      hotLoopCallSites: ["src/app/states.js#update", `${fight}#updateFishMotion`],
      callSiteEvidence: [{ path: "src/app/application.js", marker: "new Net(" },
        { path: "src/app/bootstrap.js", marker: "new Net(" }, { path: "src/app/fishing.js", marker: "new Hook(" },
        { path: "src/app/fishing.js", marker: "new Reel(" }, { path: "src/app/fishing.js", marker: "new Rod(" }],
      allocationBaseline: allocation(47, 23, 14, 0, 0, 3),
      compositionIdentityReview: true,
    }),
    [buffs]: contract({
      instanceFields: ["#activeBuffs"],
      semanticRisk: "per-frame-buff-expiry-by-delta-time-without-production-construction",
      performanceClassification: "existing-hot-loop-buff-manager",
      callSiteEvidence: [],
      allocationBaseline: allocation(1, 1, 0, 0),
    }),
    [rodPull]: contract({
      instanceFields: ["#calculator", "#result", "#state", "#strokeSnapshot", "#strokeState"],
      stableResultIdentity: true,
      semanticRisk: "per-frame-rod-pull-and-stroke-state-over-owned-calculator-and-states",
      performanceClassification: "existing-hot-loop-rod-pull-system",
      hotLoopCallSites: [`${fight}#updateRodPull`],
      callSiteEvidence: [{ path: "src/app/fishing.js", marker: "new RodPullSystem(" }],
      allocationBaseline: allocation(10, 0, 3, 0),
      compositionIdentityReview: true,
    }),
    [world]: contract({
      instanceFields: ["#backgroundRenderData", "#bgAssetIds", "#bgLoaded", "#bgOpacities", "#castableBounds", "#cols",
        "#config", "#currentDate", "#debugRevision", "#dynamicZones", "#grid", "#id", "#isDynamicBg", "#lastDebugState",
        "#lastProjector", "#locationsConfig", "#rng", "#rng", "#rows"],
      publicStateShape: ["currentLocationId"],
      semanticRisk: "per-frame-location-background-time-of-day-and-dynamic-zones-with-injected-clock",
      performanceClassification: "existing-hot-loop-location-world",
      hotLoopCallSites: ["src/app/world.js#update"],
      callSiteEvidence: [{ path: "src/app/bootstrap.js", marker: "new LocationMap(" }],
      allocationBaseline: allocation(10, 6, 7, 0, 0, 26),
    }),
  },
  migrationGates: ["six-exact-sources-and-method-shapes", "twenty-five-export-identities-and-twelve-activations",
    "thirteen-exact-completed-prefix-and-foundation-imports", "owner-created-composition-identities",
    "two-collection-identities-with-transactional-swap-and-rebuilt-index", "one-reviewed-frozen-constant",
    "twelve-exact-consumer-relationships-and-eleven-retired-bridges", "nine-retired-activations",
    "hot-loop-equivalence-against-the-stage-3.50.1-evidence", "representation-only-hot-loop-targets-and-equal-game-cycle-output",
    "all-legacy-activation-positions-preserved", "zero-config-platform-browser-dev-dependencies",
    "zero-added-hot-loop-allocations"],
}).value;

const RELEASE = Object.freeze({
  title: "Fish Tackle Inventory Repository And World Domain",
  codename: "fish-tackle-inventory-repository-world-domain",
  summary: "Batch 050 adopted the Stage 3.50.1 freeze extension and migrated the per-frame fish, tackle, inventory repository, buff, rod pull and world sources.",
  smokeContext: "Automated browser smoke under the owner's 2026-10-01 authorization: game-cycle re-executed without seals and compared with the pre-cutover output, game loaded in the built-in browser, and console errors and warnings counted.",
  notes: [
    "Adopt the Stage 3.50.1 freeze extension with its hot-loop equivalence evidence",
    "Migrate the fish entities, tackle entities, flat inventory repository, buff manager, rod pull system and location world",
    "Keep every per-frame target representation-only and the game-cycle output equal",
    "Preserve one hundred forty-eight project modules, one hundred thirty-six active activations and one hundred ninety-nine bridges",
  ],
  // Short format (owner decision 2026-10-01): 1-3 lines per release.
  changelog: [
    "- Migrated the fish and tackle entities, the flat inventory repository, buff manager, rod pull system and location world to the Domain (hot-loop evidence re-verified live; game-cycle output unchanged).",
  ],
});

module.exports = { PREFLIGHT_PROFILE, RELEASE };
