"use strict";

const { DATA } = require("../core/history_base");

// Reviewed cache and isolation contracts, applied to the manifest definitions by the runner.
// A check absent from these lists keeps the defaults: cache policy "never" (always executes) and
// "exclusive" isolation (runs alone). Entries are added only after the check's traced dependency
// record was reviewed; the runner re-verifies both contracts on every execution.

// History replays of batches up to the history base read the reconstructed release (its data trees)
// plus code and installed dependencies, which the tracer fingerprints file by file.
const HISTORY_BASE_REPLAY = Object.freeze({ policy: "snapshot", inputPaths: Object.freeze([...DATA]),
  environmentKeys: Object.freeze([]) });

const SNAPSHOT_CONTRACTS = Object.freeze([
  // Every history replay of the base except the three that rebuild dist inside the base (their writes
  // make them non-cacheable). Reviewed from the traced survey of 2026-09-28.
  Object.freeze({ contract: "history-base-replay", cache: HISTORY_BASE_REPLAY, ids: Object.freeze([
    "stage-3-batch-006-audit-fixtures",
    "stage-3-batch-006-audit-integration",
    "stage-3-batch-006-execution-plan-fixtures",
    "stage-3-batch-006-execution-plan-integration",
    "stage-3-batch-006-test-matrix-fixtures",
    "stage-3-batch-006-prebuild-fixtures",
    "stage-3-batch-006-prebuild-integration",
    "stage-3-batch-006-observations",
    "stage-3-batch-006-release-acceptance",
    "stage-3-batch-007-audit-fixtures",
    "stage-3-batch-007-audit-integration",
    "stage-3-batch-009-cutover-fixtures",
    "stage-3-batch-009-observation-fixtures",
    "stage-3-batch-009-observation",
    "stage-3-batch-009-live-runtime",
    "stage-3-batch-009-source-build-fixtures",
    "stage-3-batch-009-source-build",
    "stage-3-batch-009-planning-fixtures",
    "stage-3-batch-009-planning",
    "stage-3-batch-010-audit-fixtures",
    "stage-3-batch-010-audit",
    "stage-3-batch-010-planning-fixtures",
    "stage-3-batch-010-planning",
    "stage-3-batch-010-source-build-fixtures",
    "stage-3-batch-010-source-build",
    "stage-3-batch-010-live-runtime",
    "stage-3-batch-010-observations",
    "stage-3-batch-010-release-fixtures",
    "stage-3-batch-010-release",
    "stage-3-batch-011-audit-fixtures",
    "stage-3-batch-011-audit",
    "stage-3-batch-011-planning",
    "stage-3-batch-011-source-build-fixtures",
    "stage-3-batch-011-source-build",
    "stage-3-batch-011-cutover-fixtures",
    "stage-3-batch-011-live-runtime",
    "stage-3-batch-011-observations",
    "stage-3-batch-012-audit",
    "stage-3-batch-012-planning",
    "stage-3-batch-012-focused-parity",
    "stage-3-batch-012-source-build",
    "stage-3-batch-012-cutover-fixtures",
    "stage-3-batch-012-live-runtime",
    "stage-3-batch-012-observations",
    "stage-3-batch-013-architecture",
    "stage-3-batch-014-architecture",
    "stage-3-batch-015-architecture",
    "stage-3-batch-016-architecture",
    "stage-3-batch-017-architecture",
    "stage-3-batch-018-architecture",
    "stage-3-batch-019-architecture",
    "stage-3-batch-020-architecture",
    "stage-3-batch-021-architecture",
    "stage-3-batch-022-architecture",
    "stage-3-batch-023-architecture",
    "stage-3-batch-024-architecture",
    "stage-3-batch-025-architecture",
    "stage-3-batch-008-audit-fixtures",
    "stage-3-batch-008-audit-integration",
    "stage-3-batch-008-execution-plan-fixtures",
    "stage-3-batch-008-execution-plan-integration",
    "stage-3-batch-008-test-matrix-fixtures",
    "stage-3-batch-008-prebuild-fixtures",
    "stage-3-batch-008-prebuild-transaction-fixtures",
    "stage-3-batch-008-prebuild-integration",
    "stage-3-batch-008-source-build-fixtures",
    "stage-3-batch-008-cutover-fixtures",
    "stage-3-batch-008-live-runtime-fixtures",
    "stage-3-batch-008-observation-fixtures",
    "stage-3-batch-007-execution-plan-fixtures",
    "stage-3-batch-007-execution-plan-integration",
    "stage-3-batch-007-test-matrix-fixtures",
    "stage-3-batch-007-prebuild-fixtures",
    "stage-3-batch-007-prebuild-transaction-fixtures",
    "stage-3-batch-007-prebuild-integration",
    "stage-3-batch-007-source-build-fixtures",
    "stage-3-batch-007-cutover-fixtures",
    "stage-3-batch-007-live-runtime-fixtures",
    "stage-3-batch-007-live-runtime-integration",
    "stage-3-batch-007-acceptance",
    "stage-3-batch-007-release-acceptance",
    "stage-3-batch-008-release-acceptance",
    "stage-3-batch-008-release-fixtures",
    "stage-3-batch-009-release-acceptance",
  ]) }),
]);

// Checks reviewed to make no persistent project writes and to start no process the tracer cannot
// follow; they may run in parallel with each other. Reviewed from the traced survey of 2026-09-28:
// every check except the nine that rebuild dist (live or in the history base) and the cache
// regression check (it runs nested check runners).
const WRITERS = Object.freeze([
  "stage-3-batch-006-runtime",
  "stage-3-compatibility-runtime-integration",
  "stage-3-fishing-foundation-runtime",
  "stage-3-line-tension-runtime",
  "stage-3-reel-auto-recovery-runtime",
  "stage-3-rod-capability-runtime",
  "stage-3-batch-007-observation-fixtures",
  "stage-3-batch-007-observation-integration",
  "stage-3-batch-007-runtime-cutover",
]);
const READ_ONLY_CHECKS = Object.freeze([
  "syntax",
  "architecture-policy",
  "architecture-documentation",
  "migration-manifest-integrity",
  "migration-manifest-reconciler",
  "migration-manifest-schema-migration",
  "migration-manifest-validator",
  "legacy-symbol-provider-fixtures",
  "legacy-symbol-provider-corpus",
  "legacy-external-consumer-fixtures",
  "legacy-external-consumer-corpus",
  "provider-resolution-contract",
  "provider-resolution-fixtures",
  "provider-resolution-corpus",
  "migration-observation-persistence-fixtures",
  "migration-observation-persistence-corpus",
  "observation-graph-integrity-fixtures",
  "observation-graph-integrity-corpus",
  "classification-evidence-fixtures",
  "classification-evidence-corpus",
  "stage-1-6-migration-batch-plan",
  "approved-stage-2-batch-freeze",
  "architecture-guard-fixtures",
  "architecture-guard-corpus",
  "root-package-contract",
  "native-esm-fixture",
  "vite-fixture-build",
  "stage-1-closure",
  "stage-2-legacy-bridge-build",
  "stage-2-asset-contracts-check",
  "stage-2-dependency-contract-check",
  "stage-2-event-primitives-check",
  "stage-2-rendering-primitives-check",
  "stage-3-domain-audit-fixtures",
  "stage-3-domain-audit-schema-migration",
  "stage-3-domain-audit-corpus",
  "stage-3-induced-domain-graph-fixtures",
  "stage-3-induced-domain-graph-corpus",
  "stage-3-domain-topology-fixtures",
  "stage-3-domain-topology-corpus",
  "stage-3-domain-observation-fixtures",
  "stage-3-dependency-audit-persistence-fixtures",
  "stage-3-dependency-audit-integration",
  "stage-3-semantic-observation-fixtures",
  "stage-3-semantic-persistence-fixtures",
  "stage-3-semantic-audit-integration",
  "stage-3-compatibility-runtime-fixtures",
  "stage-3-candidate-batch-fixtures",
  "stage-3-candidate-batch-integration",
  "stage-3-approved-prefix-fixtures",
  "stage-3-approved-prefix-integration",
  "stage-3-batch-006-audit-fixtures",
  "stage-3-batch-006-audit-integration",
  "stage-3-batch-006-execution-plan-fixtures",
  "stage-3-batch-006-execution-plan-integration",
  "stage-3-batch-006-test-matrix-fixtures",
  "stage-3-batch-006-focused-test-matrix",
  "stage-3-batch-006-prebuild-fixtures",
  "stage-3-batch-006-prebuild-integration",
  "stage-3-batch-006-observations",
  "stage-3-batch-006-release-acceptance",
  "stage-3-batch-007-audit-fixtures",
  "stage-3-batch-007-audit-integration",
  "stage-3-batch-tooling-generalization",
  "stage-3-batch-009-cutover-fixtures",
  "stage-3-batch-009-observation-fixtures",
  "stage-3-batch-009-observation",
  "stage-3-batch-009-live-runtime",
  "stage-3-batch-009-source-build-fixtures",
  "stage-3-batch-009-source-build",
  "stage-3-batch-009-planning-fixtures",
  "stage-3-batch-009-planning",
  "stage-3-batch-010-audit-fixtures",
  "stage-3-batch-010-audit",
  "stage-3-batch-010-planning-fixtures",
  "stage-3-batch-010-planning",
  "stage-3-batch-010-source-build-fixtures",
  "stage-3-batch-010-source-build",
  "stage-3-batch-010-live-runtime",
  "stage-3-batch-010-observations",
  "stage-3-batch-010-release-fixtures",
  "stage-3-batch-010-release",
  "stage-3-batch-011-audit-fixtures",
  "stage-3-batch-011-audit",
  "stage-3-batch-011-planning",
  "stage-3-batch-011-source-build-fixtures",
  "stage-3-batch-011-source-build",
  "stage-3-batch-011-cutover-fixtures",
  "stage-3-batch-011-live-runtime",
  "stage-3-batch-011-observations",
  "stage-3-batch-012-audit",
  "stage-3-batch-012-planning",
  "stage-3-batch-012-focused-parity",
  "stage-3-batch-012-source-build",
  "stage-3-batch-012-cutover-fixtures",
  "stage-3-batch-012-live-runtime",
  "stage-3-batch-012-observations",
  "stage-3-batch-013-architecture",
  "stage-3-batch-014-architecture",
  "stage-3-batch-015-architecture",
  "stage-3-batch-016-architecture",
  "stage-3-batch-017-architecture",
  "stage-3-batch-018-architecture",
  "stage-3-batch-019-architecture",
  "stage-3-batch-020-architecture",
  "stage-3-batch-021-architecture",
  "stage-3-batch-022-architecture",
  "stage-3-batch-023-architecture",
  "stage-3-batch-024-architecture",
  "stage-3-batch-025-architecture",
  "stage-3-batch-026-architecture",
  "stage-3-batch-027-architecture",
  "stage-3-batch-028-architecture",
  "stage-3-batch-029-architecture",
  "stage-3-batch-030-architecture",
  "stage-3-batch-031-architecture",
  "stage-3-batch-032-architecture",
  "stage-3-batch-033-architecture",
  "stage-3-batch-034-architecture",
  "stage-3-batch-035-architecture",
  "stage-3-batch-036-architecture",
  "stage-3-batch-037-architecture",
  "stage-3-batch-038-architecture",
  "stage-3-34-review-queue-freeze",
  "stage-3-34-review-queue-freeze-fixtures",
  "stage-3-36-graph-review",
  "stage-3-prerequisite-001",
  "stage-3-prerequisite-002",
  "stage-3-prerequisite-003",
  "stage-3-prerequisite-004",
  "stage-3-prerequisite-005",
  "stage-3-prerequisite-006",
  "stage-3-prerequisite-007",
  "stage-3-prerequisite-008",
  "stage-3-prerequisite-009",
  "stage-3-prerequisite-010",
  "stage-3-prerequisite-transition-fixtures",
  "legacy-slot-split",
  "stage-3-activation-retirement-fixtures",
  "stage-3-shared-batch-tooling-negative",
  "stage-3-shared-batch-tooling-equivalence",
  "stage-3-22-post-freeze-review",
  "stage-3-batch-008-audit-fixtures",
  "stage-3-batch-008-audit-integration",
  "stage-3-batch-008-execution-plan-fixtures",
  "stage-3-batch-008-execution-plan-integration",
  "stage-3-batch-008-test-matrix-fixtures",
  "stage-3-batch-008-focused-test-matrix",
  "stage-3-batch-008-prebuild-fixtures",
  "stage-3-batch-008-prebuild-transaction-fixtures",
  "stage-3-batch-008-prebuild-integration",
  "stage-3-batch-008-source-build-fixtures",
  "stage-3-batch-008-source-build-integration",
  "stage-3-batch-008-cutover-fixtures",
  "stage-3-batch-008-runtime-cutover",
  "stage-3-batch-008-live-runtime-fixtures",
  "stage-3-batch-008-live-runtime-integration",
  "stage-3-batch-008-observation-fixtures",
  "stage-3-batch-008-observation-integration",
  "stage-3-batch-007-execution-plan-fixtures",
  "stage-3-batch-007-execution-plan-integration",
  "stage-3-batch-007-test-matrix-fixtures",
  "stage-3-batch-007-focused-test-matrix",
  "stage-3-batch-prebuild-tooling-generalization",
  "stage-3-batch-007-prebuild-fixtures",
  "stage-3-batch-007-prebuild-transaction-fixtures",
  "stage-3-batch-007-prebuild-integration",
  "stage-3-batch-007-source-build-fixtures",
  "stage-3-batch-007-source-build-integration",
  "stage-3-inventory-equip-target-batch",
  "stage-3-reel-auto-recovery-prebuild",
  "stage-3-batch-007-cutover-fixtures",
  "stage-3-batch-007-live-runtime-fixtures",
  "stage-3-batch-007-live-runtime-integration",
  "stage-3-line-tension-prebuild",
  "stage-3-rod-capability-prebuild",
  "stage-3-fishing-foundation-prebuild",
  "line-allocation",
  "float-depth",
  "inventory-lifecycle",
  "assembly-domain",
  "inventory-v2-equipment",
  "inventory-v2-equipment-hydration",
  "stage-3-batch-007-reel-retrieve-browser-probe",
  "stage-3-batch-007-acceptance",
  "stage-3-batch-007-release-acceptance",
  "stage-3-batch-008-release-acceptance",
  "stage-3-batch-008-release-fixtures",
  "stage-3-batch-009-release-acceptance",
  "inventory-v2-transaction",
  "inventory-v2-migration",
  "inventory-v2-cast-lure",
  "inventory-v2-line-allocation",
  "consumable-event-identity",
  "inventory-v2-integration",
  "inventory-v2-ui",
  "bait-effectiveness",
  "item-freshness-gameplay",
  "hook-domain-semantics",
  "item-stat-contract",
  "fish-rarity",
  "item-rarity",
  "item-rarity-roundtrip",
  "item-progression",
  "item-condition",
  "item-state-hardening",
  "degradation-colors",
  "rarity-production",
  "victory-input",
  "game-cycle",
  "devtools-links",
]);

function applyCheckPolicies(definitions) {
  const ids = new Set(definitions.map((definition) => definition.id));
  const cacheById = new Map();
  for (const { contract, cache, ids: members } of SNAPSHOT_CONTRACTS) {
    for (const id of members) {
      if (!ids.has(id)) throw new Error(`Cache contract ${contract} names an unknown check: ${id}`);
      if (cacheById.has(id)) throw new Error(`Check has two cache contracts: ${id}`);
      cacheById.set(id, cache);
    }
  }
  const readOnly = new Set(READ_ONLY_CHECKS);
  for (const id of readOnly) {
    if (!ids.has(id)) throw new Error(`Read-only isolation names an unknown check: ${id}`);
  }
  return definitions.map((definition) => ({
    ...definition,
    ...(cacheById.has(definition.id) ? { cache: cacheById.get(definition.id) } : {}),
    ...(readOnly.has(definition.id) ? { isolation: "read-only" } : {}),
  }));
}

module.exports = { applyCheckPolicies, HISTORY_BASE_REPLAY, READ_ONLY_CHECKS, SNAPSHOT_CONTRACTS, WRITERS };
