"use strict";

// Single registry of checks and suite membership; every utils/*-check.js file appears exactly once.
const CHECK_DEFINITIONS = Object.freeze([
  {
    id: "syntax",
    title: "JavaScript syntax",
    file: "utils/check-js.js",
    suites: ["quick"],
  },
  {
    id: "architecture",
    title: "Layer boundaries, import graph and host globals",
    file: "utils/architecture-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "line-allocation",
    title: "Line allocation domain",
    file: "utils/line-allocation-check.js",
    suites: ["gameplay"],
  },
  {
    id: "float-depth",
    title: "Float depth and casting",
    file: "utils/float-depth-cast-check.js",
    suites: ["gameplay"],
  },
  {
    id: "inventory-lifecycle",
    title: "Inventory compatibility lifecycle",
    file: "utils/inventory-lifecycle-check.js",
    suites: ["inventory"],
  },
  {
    id: "assembly-domain",
    title: "Item assembly domain",
    file: "utils/item-assembly-domain-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-equipment",
    title: "Inventory V2 equipment policies",
    file: "utils/inventory-v2-equipment-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-equipment-hydration",
    title: "Inventory V2 production-shaped equipment hydration",
    file: "utils/inventory-v2-equipment-hydration-check.js",
    suites: ["quick", "inventory", "inventory-v2", "gameplay"],
  },
  {
    id: "inventory-v2-transaction",
    title: "Inventory V2 transactions",
    file: "utils/inventory-v2-transaction-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-migration",
    title: "Inventory V2 migrations",
    file: "utils/inventory-v2-migration-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-save-round-trip",
    title: "Inventory save round trip (old, current and previous-schema saves)",
    file: "utils/inventory-save-round-trip-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-cast-lure",
    title: "Inventory V2 cast and lure integration",
    file: "utils/inventory-v2-cast-and-lure-check.js",
    suites: ["inventory", "inventory-v2", "gameplay"],
  },
  {
    id: "inventory-v2-line-allocation",
    title: "Inventory V2 line allocation",
    file: "utils/inventory-v2-line-allocation-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "consumable-event-identity",
    title: "Consumable event identity",
    file: "utils/consumable-event-identity-check.js",
    suites: ["inventory", "inventory-v2", "gameplay"],
  },
  {
    id: "inventory-v2-integration",
    title: "Inventory V2 application integration",
    file: "utils/inventory-v2-integration-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-ui",
    title: "Inventory V2 UI",
    file: "utils/inventory-v2-ui-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "bait-effectiveness",
    title: "Contextual bait effectiveness",
    file: "utils/bait-effectiveness-check.js",
    suites: ["items", "gameplay", "inventory-v2"],
  },
  {
    id: "item-freshness-gameplay",
    title: "Gameplay-backed bait freshness",
    file: "utils/item-freshness-gameplay-check.js",
    suites: ["items", "gameplay", "inventory-v2"],
  },
  {
    id: "hook-domain-semantics",
    title: "Hook domain semantics",
    file: "utils/hook-domain-semantics-check.js",
    suites: ["items", "gameplay"],
  },
  {
    id: "item-stat-contract",
    title: "Final item stat contract",
    file: "utils/item-stat-contract-check.js",
    suites: ["quick", "items", "inventory-v2"],
  },
  {
    id: "fish-rarity",
    title: "Fish rarity",
    file: "utils/fish-rarity-check.js",
    suites: ["items"],
  },
  {
    id: "item-rarity",
    title: "Item rarity",
    file: "utils/item-rarity-check.js",
    suites: ["items"],
  },
  {
    id: "item-rarity-roundtrip",
    title: "Item rarity snapshot and Inventory V2",
    file: "utils/item-rarity-roundtrip-check.js",
    suites: ["quick", "inventory", "inventory-v2", "items"],
  },
  {
    id: "item-progression",
    title: "Item progression",
    file: "utils/item-progression-check.js",
    suites: ["items"],
  },
  {
    id: "item-condition",
    title: "Item condition",
    file: "utils/item-condition-check.js",
    suites: ["items"],
  },
  {
    id: "item-state-hardening",
    title: "Canonical item instance state and persistence",
    file: "utils/item-state-hardening-check.js",
    suites: ["inventory", "inventory-v2", "items"],
  },
  {
    id: "degradation-colors",
    title: "Degradation colors",
    file: "utils/degradation-color-check.js",
    suites: ["items"],
  },
  {
    id: "rarity-production",
    title: "Production rarity configuration",
    file: "utils/rarity-production-check.js",
    suites: ["quick", "items"],
  },
  {
    id: "victory-input",
    title: "Victory input",
    file: "utils/victory-input-check.js",
    suites: ["gameplay"],
  },
  {
    id: "game-cycle",
    title: "Full game cycle",
    file: "utils/game-cycle-check.js",
    suites: ["quick", "gameplay"],
  },
  {
    id: "reel-retrieve-diagnostic",
    title: "DEV reel retrieve diagnostic lifecycle",
    file: "utils/reel-retrieve-diagnostic-check.js",
    suites: ["tools"],
  },
  {
    id: "devtools-links",
    title: "DevTools linked parameters",
    file: "utils/dev-tools-linked-parameter-check.js",
    suites: ["tools"],
  },
  {
    id: "platform-runtime",
    title: "Platform assets and frame timing",
    file: "utils/platform-runtime-check.js",
    suites: ["quick", "gameplay"],
  },
  {
    id: "config-schema",
    title: "Configuration schema validation (production, DEV and DEV reporter)",
    file: "utils/config-schema-check.js",
    suites: ["quick", "gameplay"],
  },
  {
    id: "config-runtime",
    title: "Live configuration and override runtime",
    file: "utils/config-runtime-check.js",
    suites: ["quick", "gameplay"],
  },
]);

module.exports = { CHECK_DEFINITIONS };
