const CHECK_DEFINITIONS = Object.freeze([
  {
    id: "syntax",
    title: "JavaScript syntax",
    file: "utils/check-js.js",
    suites: ["quick"],
  },
  {
    id: "architecture-policy",
    title: "Architecture policy",
    file: "utils/architecture/architecture-policy-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "architecture-documentation",
    title: "Architecture documentation sync",
    file: "utils/architecture/architecture-documentation-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "migration-manifest-integrity",
    title: "Migration manifest integrity",
    file: "utils/architecture/migration-manifest-integrity-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "migration-manifest-reconciler",
    title: "Migration manifest reconciliation",
    file: "utils/architecture/migration-manifest-reconciler-check.js",
    suites: ["architecture"],
  },
  {
    id: "migration-manifest-schema-migration",
    title: "Migration manifest schema migration",
    file: "utils/architecture/migration-manifest-schema-migration-check.js",
    suites: ["architecture"],
  },
  {
    id: "migration-manifest-validator",
    title: "Migration manifest validator scenarios",
    file: "utils/architecture/migration-manifest-validator-check.js",
    suites: ["architecture"],
  },
  {
    id: "legacy-symbol-provider-fixtures",
    title: "Legacy symbol provider scanner fixtures",
    file: "utils/architecture/legacy-symbol-provider-scanner-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "legacy-symbol-provider-corpus",
    title: "Legacy symbol provider read-only corpus scan",
    file: "utils/architecture/legacy-symbol-provider-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "legacy-external-consumer-fixtures",
    title: "Legacy external consumer scanner fixtures",
    file: "utils/architecture/legacy-external-consumer-scanner-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "legacy-external-consumer-corpus",
    title: "Legacy external consumer read-only corpus scan",
    file: "utils/architecture/legacy-external-consumer-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "provider-resolution-contract",
    title: "Provider resolution executable contract",
    file: "utils/architecture/provider-resolution-contract-check.js",
    suites: ["architecture"],
  },
  {
    id: "provider-resolution-fixtures",
    title: "Provider resolution engine fixtures",
    file: "utils/architecture/provider-resolution-engine-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "provider-resolution-corpus",
    title: "Provider resolution read-only corpus graph",
    file: "utils/architecture/provider-resolution-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "migration-observation-persistence-fixtures",
    title: "Migration observation persistence fixtures",
    file: "utils/architecture/migration-observation-persistence-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "migration-observation-persistence-corpus",
    title: "Migration observation persistence corpus sync",
    file: "utils/architecture/migration-observation-persistence-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "observation-graph-integrity-fixtures",
    title: "Observation graph integrity fixtures",
    file: "utils/architecture/observation-graph-integrity-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "observation-graph-integrity-corpus",
    title: "Observation graph integrity and reverse consumers",
    file: "utils/architecture/observation-graph-integrity-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "classification-evidence-fixtures",
    title: "Architecture classification evidence fixtures",
    file: "utils/architecture/classification-evidence-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "classification-evidence-corpus",
    title: "Architecture classification read-only evidence corpus",
    file: "utils/architecture/classification-evidence-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-1-6-migration-batch-plan",
    title: "Stage 1.6 concrete migration batch plan",
    file: "utils/architecture/stage-1-6-migration-batch-plan-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "approved-stage-2-batch-freeze",
    title: "Approved Stage 2 migration batch freeze",
    file: "utils/architecture/approved-stage-2-batch-freeze-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "architecture-guard-fixtures",
    title: "Architecture guard shared fixture matrix",
    file: "utils/architecture/architecture-guard-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "architecture-guard-corpus",
    title: "Unified architecture guard corpus",
    file: "utils/architecture/architecture-guard-corpus-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "root-package-contract",
    title: "Reproducible root package and lockfile contract",
    file: "utils/architecture/package-contract-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "native-esm-fixture",
    title: "Isolated native ESM fixture runtime",
    file: "utils/architecture/native-esm-fixture-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "vite-fixture-build",
    title: "Vite synthetic fixture build boundary",
    file: "utils/architecture/vite-fixture-build-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-1-closure",
    title: "Stage 1 closure and evidence freeze",
    file: "utils/architecture/stage-1-closure-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "line-allocation",
    title: "Line allocation domain",
    file: "utils/line-allocation-check.js",
    suites: ["gameplay"],
  },
  {
    id: "float-depth",
    title: "Float depth and casting",
    file: "utils/float-depth-cast-check.js",
    suites: ["gameplay"],
  },
  {
    id: "inventory-lifecycle",
    title: "Inventory compatibility lifecycle",
    file: "utils/inventory-lifecycle-check.js",
    suites: ["inventory"],
  },
  {
    id: "assembly-domain",
    title: "Item assembly domain",
    file: "utils/item-assembly-domain-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-equipment",
    title: "Inventory V2 equipment policies",
    file: "utils/inventory-v2-equipment-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-transaction",
    title: "Inventory V2 transactions",
    file: "utils/inventory-v2-transaction-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-migration",
    title: "Inventory V2 migrations",
    file: "utils/inventory-v2-migration-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-cast-lure",
    title: "Inventory V2 cast and lure integration",
    file: "utils/inventory-v2-cast-and-lure-check.js",
    suites: ["inventory", "inventory-v2", "gameplay"],
  },
  {
    id: "inventory-v2-line-allocation",
    title: "Inventory V2 line allocation",
    file: "utils/inventory-v2-line-allocation-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "consumable-event-identity",
    title: "Consumable event identity",
    file: "utils/consumable-event-identity-check.js",
    suites: ["inventory", "inventory-v2", "gameplay"],
  },
  {
    id: "inventory-v2-integration",
    title: "Inventory V2 application integration",
    file: "utils/inventory-v2-integration-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-ui",
    title: "Inventory V2 UI",
    file: "utils/inventory-v2-ui-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "bait-effectiveness",
    title: "Contextual bait effectiveness",
    file: "utils/bait-effectiveness-check.js",
    suites: ["items", "gameplay", "inventory-v2"],
  },
  {
    id: "item-freshness-gameplay",
    title: "Gameplay-backed bait freshness",
    file: "utils/item-freshness-gameplay-check.js",
    suites: ["items", "gameplay", "inventory-v2"],
  },
  {
    id: "hook-domain-semantics",
    title: "Hook domain semantics",
    file: "utils/hook-domain-semantics-check.js",
    suites: ["items", "gameplay"],
  },
  {
    id: "item-stat-contract",
    title: "Final item stat contract",
    file: "utils/item-stat-contract-check.js",
    suites: ["quick", "items", "inventory-v2"],
  },
  {
    id: "fish-rarity",
    title: "Fish rarity",
    file: "utils/fish-rarity-check.js",
    suites: ["items"],
  },
  {
    id: "item-rarity",
    title: "Item rarity",
    file: "utils/item-rarity-check.js",
    suites: ["items"],
  },
  {
    id: "item-rarity-roundtrip",
    title: "Item rarity snapshot and Inventory V2",
    file: "utils/item-rarity-roundtrip-check.js",
    suites: ["quick", "inventory", "inventory-v2", "items"],
  },
  {
    id: "item-progression",
    title: "Item progression",
    file: "utils/item-progression-check.js",
    suites: ["items"],
  },
  {
    id: "item-condition",
    title: "Item condition",
    file: "utils/item-condition-check.js",
    suites: ["items"],
  },
  {
    id: "item-state-hardening",
    title: "Canonical item instance state and persistence",
    file: "utils/item-state-hardening-check.js",
    suites: ["inventory", "inventory-v2", "items"],
  },
  {
    id: "degradation-colors",
    title: "Degradation colors",
    file: "utils/degradation-color-check.js",
    suites: ["items"],
  },
  {
    id: "rarity-production",
    title: "Production rarity configuration",
    file: "utils/rarity-production-check.js",
    suites: ["quick", "items"],
  },
  {
    id: "victory-input",
    title: "Victory input",
    file: "utils/victory-input-check.js",
    suites: ["gameplay"],
  },
  {
    id: "game-cycle",
    title: "Full game cycle",
    file: "utils/game-cycle-check.js",
    suites: ["gameplay"],
  },
  {
    id: "devtools-links",
    title: "DevTools linked parameters",
    file: "utils/dev-tools-linked-parameter-check.js",
    suites: ["tools"],
  },
]);

module.exports = { CHECK_DEFINITIONS };
