const CHECK_DEFINITIONS = Object.freeze([
  {
    id: "syntax",
    title: "JavaScript syntax",
    file: "utils/check-js.js",
    suites: ["quick"],
  },
  {
    id: "architecture-policy",
    title: "Architecture policy",
    file: "utils/architecture/architecture-policy-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "architecture-documentation",
    title: "Architecture documentation sync",
    file: "utils/architecture/architecture-documentation-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "migration-manifest-integrity",
    title: "Migration manifest integrity",
    file: "utils/architecture/migration-manifest-integrity-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "migration-manifest-reconciler",
    title: "Migration manifest reconciliation",
    file: "utils/architecture/migration-manifest-reconciler-check.js",
    suites: ["architecture"],
  },
  {
    id: "migration-manifest-schema-migration",
    title: "Migration manifest schema migration",
    file: "utils/architecture/migration-manifest-schema-migration-check.js",
    suites: ["architecture"],
  },
  {
    id: "migration-manifest-validator",
    title: "Migration manifest validator scenarios",
    file: "utils/architecture/migration-manifest-validator-check.js",
    suites: ["architecture"],
  },
  {
    id: "legacy-symbol-provider-fixtures",
    title: "Legacy symbol provider scanner fixtures",
    file: "utils/architecture/legacy-symbol-provider-scanner-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "legacy-symbol-provider-corpus",
    title: "Legacy symbol provider read-only corpus scan",
    file: "utils/architecture/legacy-symbol-provider-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "legacy-external-consumer-fixtures",
    title: "Legacy external consumer scanner fixtures",
    file: "utils/architecture/legacy-external-consumer-scanner-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "legacy-external-consumer-corpus",
    title: "Legacy external consumer read-only corpus scan",
    file: "utils/architecture/legacy-external-consumer-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "provider-resolution-contract",
    title: "Provider resolution executable contract",
    file: "utils/architecture/provider-resolution-contract-check.js",
    suites: ["architecture"],
  },
  {
    id: "provider-resolution-fixtures",
    title: "Provider resolution engine fixtures",
    file: "utils/architecture/provider-resolution-engine-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "provider-resolution-corpus",
    title: "Provider resolution read-only corpus graph",
    file: "utils/architecture/provider-resolution-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "migration-observation-persistence-fixtures",
    title: "Migration observation persistence fixtures",
    file: "utils/architecture/migration-observation-persistence-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "migration-observation-persistence-corpus",
    title: "Migration observation persistence corpus sync",
    file: "utils/architecture/migration-observation-persistence-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "observation-graph-integrity-fixtures",
    title: "Observation graph integrity fixtures",
    file: "utils/architecture/observation-graph-integrity-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "observation-graph-integrity-corpus",
    title: "Observation graph integrity and reverse consumers",
    file: "utils/architecture/observation-graph-integrity-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "classification-evidence-fixtures",
    title: "Architecture classification evidence fixtures",
    file: "utils/architecture/classification-evidence-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "classification-evidence-corpus",
    title: "Architecture classification read-only evidence corpus",
    file: "utils/architecture/classification-evidence-corpus-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-1-6-migration-batch-plan",
    title: "Stage 1.6 concrete migration batch plan",
    file: "utils/architecture/stage-1-6-migration-batch-plan-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "approved-stage-2-batch-freeze",
    title: "Approved Stage 2 migration batch freeze",
    file: "utils/architecture/approved-stage-2-batch-freeze-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "architecture-guard-fixtures",
    title: "Architecture guard shared fixture matrix",
    file: "utils/architecture/architecture-guard-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "architecture-guard-corpus",
    title: "Unified architecture guard corpus",
    file: "utils/architecture/architecture-guard-corpus-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "root-package-contract",
    title: "Reproducible root package and lockfile contract",
    file: "utils/architecture/package-contract-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "native-esm-fixture",
    title: "Isolated native ESM fixture runtime",
    file: "utils/architecture/native-esm-fixture-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "vite-fixture-build",
    title: "Vite synthetic fixture build boundary",
    file: "utils/architecture/vite-fixture-build-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-1-closure",
    title: "Stage 1 closure and evidence freeze",
    file: "utils/architecture/stage-1-closure-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-2-legacy-bridge-build",
    title: "Stage 2 classic bridge build foundation",
    file: "utils/architecture/stage-2-legacy-bridge-build-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-2-asset-contracts-check",
    title: "Stage 2.1 engine asset contracts",
    file: "utils/architecture/stage-2-asset-contracts-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-2-dependency-contract-check",
    title: "Stage 2.2 engine dependency contract",
    file: "utils/architecture/stage-2-dependency-contract-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-2-event-primitives-check",
    title: "Stage 2.3 engine event primitives",
    file: "utils/architecture/stage-2-event-primitives-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-2-rendering-primitives-check",
    title: "Stage 2.4 engine rendering primitives",
    file: "utils/architecture/stage-2-rendering-primitives-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-domain-audit-fixtures",
    title: "Stage 3 domain audit contract fixtures",
    file: "utils/architecture/stage-3-domain-audit-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-domain-audit-schema-migration",
    title: "Stage 3.0.2.1 dependency audit schema migration",
    file: "utils/architecture/stage-3-domain-audit-schema-migration-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-domain-audit-corpus",
    title: "Stage 3.0.1 conservative domain inventory",
    file: "utils/architecture/stage-3-domain-audit-corpus-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-induced-domain-graph-fixtures",
    title: "Stage 3.0.2.2 induced domain graph fixtures",
    file: "utils/architecture/stage-3-induced-domain-graph-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-induced-domain-graph-corpus",
    title: "Stage 3.0.2.2 induced domain graph corpus",
    file: "utils/architecture/stage-3-induced-domain-graph-corpus-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-domain-topology-fixtures",
    title: "Stage 3.0.2.3 domain SCC and depth fixtures",
    file: "utils/architecture/stage-3-domain-topology-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-domain-topology-corpus",
    title: "Stage 3.0.2.3 domain SCC and depth corpus",
    file: "utils/architecture/stage-3-domain-topology-corpus-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-domain-observation-fixtures",
    title: "Stage 3.0.2.4 capability, availability and effect fixtures",
    file: "utils/architecture/stage-3-domain-observation-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-dependency-audit-persistence-fixtures",
    title: "Stage 3.0.2.5 dependency audit persistence fixtures",
    file: "utils/architecture/stage-3-dependency-audit-persistence-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-dependency-audit-integration",
    title: "Stage 3.0.2.6 dependency audit integration",
    file: "utils/architecture/stage-3-dependency-audit-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-semantic-observation-fixtures",
    title: "Stage 3.0.3 state, config and performance fixtures",
    file: "utils/architecture/stage-3-semantic-observation-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-semantic-persistence-fixtures",
    title: "Stage 3.0.3 semantic persistence fixtures",
    file: "utils/architecture/stage-3-semantic-persistence-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-semantic-audit-integration",
    title: "Stage 3.0.3 semantic audit integration",
    file: "utils/architecture/stage-3-semantic-audit-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-compatibility-runtime-fixtures",
    title: "Stage 3.0.4 cumulative compatibility runtime fixtures",
    file: "utils/architecture/stage-3-compatibility-runtime-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-compatibility-runtime-integration",
    title: "Stage 3.0.4 cumulative compatibility runtime integration",
    file: "utils/architecture/stage-3-compatibility-runtime-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-candidate-batch-fixtures",
    title: "Stage 3.0.5 candidate batch policy and contract fixtures",
    file: "utils/architecture/stage-3-candidate-batch-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-candidate-batch-integration",
    title: "Stage 3.0.5 candidate batch corpus and coverage",
    file: "utils/architecture/stage-3-candidate-batch-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-approved-prefix-fixtures",
    title: "Stage 3.0.6 approved-prefix contract fixtures",
    file: "utils/architecture/stage-3-approved-prefix-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-approved-prefix-integration",
    title: "Stage 3.0.6 approved-prefix freeze integration",
    file: "utils/architecture/stage-3-approved-prefix-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-006-audit-fixtures",
    title: "Stage 3.6.1 dependency/state audit contract fixtures",
    file: "utils/architecture/stage-3-batch-006-audit-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-006-audit-integration",
    title: "Stage 3.6.1 dependency/state audit integration",
    file: "utils/architecture/stage-3-batch-006-audit-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-006-execution-plan-fixtures",
    title: "Stage 3.6.2 atomic execution-plan contract fixtures",
    file: "utils/architecture/stage-3-batch-006-execution-plan-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-006-execution-plan-integration",
    title: "Stage 3.6.2 atomic execution-plan integration",
    file: "utils/architecture/stage-3-batch-006-execution-plan-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-006-test-matrix-fixtures",
    title: "Stage 3.6.3 focused test-matrix contract fixtures",
    file: "utils/architecture/stage-3-batch-006-test-matrix-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-006-focused-test-matrix",
    title: "Stage 3.6.3 executable focused behavior and compatibility matrix",
    file: "utils/architecture/stage-3-batch-006-focused-test-matrix-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-batch-006-prebuild-fixtures",
    title: "Stage 3.6.4 pre-build lifecycle contract fixtures",
    file: "utils/architecture/stage-3-batch-006-prebuild-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-006-prebuild-integration",
    title: "Stage 3.6.4 pre-build metadata and active-runtime separation",
    file: "utils/architecture/stage-3-batch-006-prebuild-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-006-runtime",
    title: "Stage 3.6.5/3.6.6 atomic ESM cutover and cumulative runtime",
    file: "utils/architecture/stage-3-batch-006-runtime-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-batch-006-observations",
    title: "Stage 3.6.7 observation and Manifest reconciliation",
    file: "utils/architecture/stage-3-batch-006-observation-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-006-release-acceptance",
    title: "Stage 3.6.8 release acceptance and batch completion",
    file: "utils/architecture/stage-3-batch-006-release-acceptance-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-007-audit-fixtures",
    title: "Stage 3.7.0 dependency/state/performance audit contract fixtures",
    file: "utils/architecture/stage-3-batch-007-audit-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-audit-integration",
    title: "Stage 3.7.0 dependency/state/performance audit integration",
    file: "utils/architecture/stage-3-batch-007-audit-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-tooling-generalization",
    title: "Stage 3.8.0 explicit generic batch tooling and historical byte stability",
    file: "utils/architecture/stage-3-batch-tooling-generalization-check.js",
    suites: ["quick", "architecture"],
  },
  {
      id: "stage-3-batch-009-cutover-fixtures",
      title: "Stage 3.9.5–3.9.6 exact transaction rollback and live failure fixtures",
      file: "utils/architecture/stage-3-batch-009-cutover-fixture-check.js",
      suites: ["architecture"],
      },
      {
        id: "stage-3-batch-009-observation-fixtures",
        title: "Stage 3.9.7 exact observation delta, immutable history and rollback fixtures",
        file: "utils/architecture/stage-3-batch-009-observation-fixture-check.js",
        suites: ["architecture"],
      },
      {
        id: "stage-3-batch-009-observation",
        title: "Stage 3.9.7 full live observation and Manifest reconciliation",
        file: "utils/architecture/stage-3-batch-009-observation-integration-check.js",
        suites: ["quick", "architecture"],
      },
    {
      id: "stage-3-batch-009-live-runtime",
      title: "Stage 3.9.5–3.9.6 actual published runtime identity, timing and state",
      file: "utils/architecture/stage-3-batch-009-live-runtime-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-009-source-build-fixtures",
      title: "Stage 3.9.3–3.9.4 isolated prebuild and candidate failure fixtures",
      file: "utils/architecture/stage-3-batch-009-source-build-fixture-check.js",
      suites: ["architecture"],
    },
    {
      id: "stage-3-batch-009-source-build",
      title: "Stage 3.9.3–3.9.4 exact live prebuild and deterministic isolated candidate build",
      file: "utils/architecture/stage-3-batch-009-source-build-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-009-planning-fixtures",
    title: "Stage 3.9.0–3.9.2 audit, execution and focused contract negative fixtures",
    file: "utils/architecture/stage-3-batch-009-planning-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-009-planning",
    title: "Stage 3.9.0–3.9.2 live preflight and isolated ESM behavior/identity matrix",
    file: "utils/architecture/stage-3-batch-009-planning-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-010-audit-fixtures",
    title: "Stage 3.10.0 source, dependency and evidence negative fixtures",
    file: "utils/architecture/stage-3-batch-010-audit-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-010-audit",
    title: "Stage 3.10.0 deterministic live preflight audit replay",
    file: "utils/architecture/stage-3-batch-010-audit-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-010-planning-fixtures",
    title: "Stage 3.10.1–3.10.2 plan, matrix and parity negative fixtures",
    file: "utils/architecture/stage-3-batch-010-planning-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-010-planning",
    title: "Stage 3.10.1–3.10.2 exact execution plan and focused ESM parity",
    file: "utils/architecture/stage-3-batch-010-planning-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-010-source-build-fixtures",
    title: "Stage 3.10.4–3.10.5 source, output and atomic publication negative fixtures",
    file: "utils/architecture/stage-3-batch-010-source-build-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-010-source-build",
    title: "Stage 3.10.4 deterministic candidate build and evaluation count",
    file: "utils/architecture/stage-3-batch-010-source-build-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-010-live-runtime",
    title: "Stage 3.10.6 published runtime identity, timing and allocation parity",
    file: "utils/architecture/stage-3-batch-010-live-runtime-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-010-observations",
    title: "Stage 3.10.7 live observation and Manifest reconciliation",
    file: "utils/architecture/stage-3-batch-010-observation-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-010-release-fixtures",
    title: "Stage 3.10.9 release transition and publication rollback fixtures",
    file: "utils/architecture/stage-3-batch-010-release-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-010-release",
    title: "Stage 3.10.9 release closure, browser proof and completed prefix",
    file: "utils/architecture/stage-3-batch-010-release-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-011-audit-fixtures",
    title: "Stage 3.11.0 source, state and evidence negative fixtures",
    file: "utils/architecture/stage-3-batch-011-audit-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-011-audit",
    title: "Stage 3.11.0 deterministic five-module preflight replay",
    file: "utils/architecture/stage-3-batch-011-audit-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-011-planning",
    title: "Stage 3.11.1–3.11.2 atomic plan and focused behavior matrix",
    file: "utils/architecture/stage-3-batch-011-planning-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-011-source-build-fixtures",
    title: "Stage 3.11.4 candidate failure isolation fixtures",
    file: "utils/architecture/stage-3-batch-011-source-build-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-011-source-build",
    title: "Stage 3.11.4 deterministic candidate and evaluation count",
    file: "utils/architecture/stage-3-batch-011-source-build-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-011-cutover-fixtures",
    title: "Stage 3.11.5 atomic cutover rollback boundaries",
    file: "utils/architecture/stage-3-batch-011-cutover-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-011-live-runtime",
    title: "Stage 3.11.6 published runtime identity, timing and state parity",
    file: "utils/architecture/stage-3-batch-011-live-runtime-check.js",
    suites: ["quick", "architecture"],
  },
    {
      id: "stage-3-batch-011-observations",
      title: "Stage 3.11.7 live observation and Manifest reconciliation",
      file: "utils/architecture/stage-3-batch-011-observation-integration-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-012-audit",
      title: "Stage 3.12.0 reviewed side effects and deterministic preflight",
      file: "utils/architecture/stage-3-batch-012-audit-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-012-planning",
      title: "Stage 3.12.1–3.12.2 exact plan and behavior matrix",
      file: "utils/architecture/stage-3-batch-012-planning-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-012-focused-parity",
      title: "Stage 3.12.2 classic and ESM behavior parity",
      file: "utils/architecture/stage-3-batch-012-focused-parity-check.js",
      suites: ["architecture"],
    },
    {
      id: "stage-3-batch-012-source-build",
      title: "Stage 3.12.4 reproducible candidate and evaluation count",
      file: "utils/architecture/stage-3-batch-012-source-build-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-012-cutover-fixtures",
      title: "Stage 3.12.5 atomic cutover failure boundaries",
      file: "utils/architecture/stage-3-batch-012-cutover-fixture-check.js",
      suites: ["architecture"],
    },
    {
      id: "stage-3-batch-012-live-runtime",
      title: "Stage 3.12.6 identity, timing and state parity",
      file: "utils/architecture/stage-3-batch-012-live-runtime-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-012-observations",
      title: "Stage 3.12.7 Manifest, graph and guard reconciliation",
      file: "utils/architecture/stage-3-batch-012-observation-integration-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-013-architecture",
      title: "Stage 3.13.0–3.13.7 fishing domain migration and rollback gates",
      file: "utils/architecture/stage-3-batch-013-architecture-check.js",
      suites: ["quick", "architecture"],
    },
    {
      id: "stage-3-batch-014-architecture",
      title: "Stage 3.14.0–3.14.7 fishing stamina and tackle domain migration and rollback gates",
      file: "utils/architecture/stage-3-batch-014-architecture-check.js",
      suites: ["quick", "architecture"],
    },
  {
    id: "stage-3-batch-008-audit-fixtures",
    title: "Stage 3.8.0 batch-008 dependency/state preflight fixtures",
    file: "utils/architecture/stage-3-batch-008-audit-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-audit-integration",
    title: "Stage 3.8.0 batch-008 dependency/state preflight integration",
    file: "utils/architecture/stage-3-batch-008-audit-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-008-execution-plan-fixtures",
    title: "Stage 3.8.1 atomic execution-plan contract fixtures",
    file: "utils/architecture/stage-3-batch-008-execution-plan-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-execution-plan-integration",
    title: "Stage 3.8.1 SCM-backed atomic execution plan",
    file: "utils/architecture/stage-3-batch-008-execution-plan-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-008-test-matrix-fixtures",
    title: "Stage 3.8.2 focused test-matrix contract fixtures",
    file: "utils/architecture/stage-3-batch-008-test-matrix-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-focused-test-matrix",
    title: "Stage 3.8.2 classic and temporary-ESM behavior/state matrix",
    file: "utils/architecture/stage-3-batch-008-focused-test-matrix-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-batch-008-prebuild-fixtures",
    title: "Stage 3.8.3 exact prebuild contract fixtures",
    file: "utils/architecture/stage-3-batch-008-prebuild-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-prebuild-transaction-fixtures",
    title: "Stage 3.8.3 atomic metadata-open rollback fixtures",
    file: "utils/architecture/stage-3-batch-008-prebuild-transaction-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-prebuild-integration",
    title: "Stage 3.8.3 prebuild-open state and frozen runtime topology",
    file: "utils/architecture/stage-3-batch-008-prebuild-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-008-source-build-fixtures",
    title: "Stage 3.8.4 source/build negative and failure-recovery fixtures",
    file: "utils/architecture/stage-3-batch-008-source-build-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-source-build-integration",
    title: "Stage 3.8.4 actual candidate build, identity and pending Manifest",
    file: "utils/architecture/stage-3-batch-008-source-build-integration-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-batch-008-cutover-fixtures",
    title: "Stage 3.8.5 full transaction rollback boundaries",
    file: "utils/architecture/stage-3-batch-008-cutover-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-runtime-cutover",
    title: "Stage 3.8.5 actual cutover topology and cumulative regressions",
    file: "utils/architecture/stage-3-batch-008-runtime-cutover-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-batch-008-live-runtime-fixtures",
    title: "Stage 3.8.6 evaluation, timing, state and allocation negative fixtures",
    file: "utils/architecture/stage-3-batch-008-live-runtime-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-live-runtime-integration",
    title: "Stage 3.8.6 actual live runtime and immutable evidence replay",
    file: "utils/architecture/stage-3-batch-008-live-runtime-integration-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-batch-008-observation-fixtures",
    title: "Stage 3.8.7 exact facts, metadata boundaries and transactional rollback",
    file: "utils/architecture/stage-3-batch-008-observation-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-008-observation-integration",
    title: "Stage 3.8.7 current observation persistence and historical evidence",
    file: "utils/architecture/stage-3-batch-008-observation-integration-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-batch-007-execution-plan-fixtures",
    title: "Stage 3.7.1 atomic execution-plan contract fixtures",
    file: "utils/architecture/stage-3-batch-007-execution-plan-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-execution-plan-integration",
    title: "Stage 3.7.1 SCM-backed atomic execution plan",
    file: "utils/architecture/stage-3-batch-007-execution-plan-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-007-test-matrix-fixtures",
    title: "Stage 3.7.2 focused test-matrix contract fixtures",
    file: "utils/architecture/stage-3-batch-007-test-matrix-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-focused-test-matrix",
    title: "Stage 3.7.2 classic and temporary-ESM behavior/compatibility matrix",
    file: "utils/architecture/stage-3-batch-007-focused-test-matrix-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-batch-prebuild-tooling-generalization",
    title: "Stage 3.7.3 reusable prebuild tooling and batch-006 byte stability",
    file: "utils/architecture/stage-3-batch-prebuild-tooling-generalization-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-007-prebuild-fixtures",
    title: "Stage 3.7.3 exact prebuild contract fixtures",
    file: "utils/architecture/stage-3-batch-007-prebuild-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-prebuild-transaction-fixtures",
    title: "Stage 3.7.3 transactional metadata replacement fixtures",
    file: "utils/architecture/stage-3-batch-007-prebuild-transaction-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-prebuild-integration",
    title: "Stage 3.7.3 prebuild-open state and frozen runtime topology",
    file: "utils/architecture/stage-3-batch-007-prebuild-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-007-source-build-fixtures",
    title: "Stage 3.7.4 representation target and candidate-build fixtures",
    file: "utils/architecture/stage-3-batch-007-source-build-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-source-build-integration",
    title: "Stage 3.7.4 target source and isolated candidate build validation",
    file: "utils/architecture/stage-3-batch-007-source-build-integration-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-inventory-equip-target-batch",
    title: "Stage 3.1 inventory equip-target domain batch",
    file: "utils/architecture/stage-3-inventory-equip-target-batch-check.js",
    suites: ["quick", "architecture", "inventory"],
  },
  {
    id: "stage-3-reel-auto-recovery-prebuild",
    title: "Stage 3.2 reel auto-recovery pre-build contract",
    file: "utils/architecture/stage-3-reel-auto-recovery-prebuild-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-007-cutover-fixtures",
    title: "Stage 3.7.5 atomic runtime cutover fixtures",
    file: "utils/architecture/stage-3-batch-007-cutover-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-runtime-cutover",
    title: "Stage 3.7.5 atomic runtime cutover",
    file: "utils/architecture/stage-3-batch-007-runtime-cutover-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-007-live-runtime-fixtures",
    title: "Stage 3.7.6 live identity/state/performance fixtures",
    file: "utils/architecture/stage-3-batch-007-live-runtime-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-live-runtime-integration",
    title: "Stage 3.7.6 live identity/state/performance integration",
    file: "utils/architecture/stage-3-batch-007-live-runtime-integration-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-007-observation-fixtures",
    title: "Stage 3.7.7 observation reconciliation and semantic-gate fixtures",
    file: "utils/architecture/stage-3-batch-007-observation-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-007-observation-integration",
    title: "Stage 3.7.7 mechanical reconciliation (not release approval)",
    file: "utils/architecture/finalize-stage-3-batch-007-observations.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-reel-auto-recovery-runtime",
    title: "Stage 3.2 reel auto-recovery post-build runtime",
    file: "utils/architecture/stage-3-reel-auto-recovery-runtime-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-line-tension-prebuild",
    title: "Stage 3.3 line-tension pre-build contract",
    file: "utils/architecture/stage-3-line-tension-prebuild-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-line-tension-runtime",
    title: "Stage 3.3 line-tension post-build runtime",
    file: "utils/architecture/stage-3-line-tension-runtime-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-rod-capability-prebuild",
    title: "Stage 3.4 rod-capability pre-build contract",
    file: "utils/architecture/stage-3-rod-capability-prebuild-check.js",
    suites: ["quick", "architecture", "inventory-v2"],
  },
  {
    id: "stage-3-rod-capability-runtime",
    title: "Stage 3.4 rod-capability post-build runtime",
    file: "utils/architecture/stage-3-rod-capability-runtime-check.js",
    suites: ["quick", "architecture", "inventory-v2"],
  },
  {
    id: "stage-3-fishing-foundation-prebuild",
    title: "Stage 3.5 fishing-foundation pre-build contract",
    file: "utils/architecture/stage-3-fishing-foundation-prebuild-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "stage-3-fishing-foundation-runtime",
    title: "Stage 3.5 fishing-foundation post-build runtime",
    file: "utils/architecture/stage-3-fishing-foundation-runtime-check.js",
    suites: ["quick", "architecture", "gameplay"],
  },
  {
    id: "line-allocation",
    title: "Line allocation domain",
    file: "utils/line-allocation-check.js",
    suites: ["gameplay"],
  },
  {
    id: "float-depth",
    title: "Float depth and casting",
    file: "utils/float-depth-cast-check.js",
    suites: ["gameplay"],
  },
  {
    id: "inventory-lifecycle",
    title: "Inventory compatibility lifecycle",
    file: "utils/inventory-lifecycle-check.js",
    suites: ["inventory"],
  },
  {
    id: "assembly-domain",
    title: "Item assembly domain",
    file: "utils/item-assembly-domain-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-equipment",
    title: "Inventory V2 equipment policies",
    file: "utils/inventory-v2-equipment-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-equipment-hydration",
    title: "Inventory V2 production-shaped equipment hydration",
    file: "utils/inventory-v2-equipment-hydration-check.js",
    suites: ["quick", "architecture", "inventory", "inventory-v2", "gameplay"],
  },
  {
    id: "stage-3-batch-007-reel-retrieve-browser-probe",
    title: "Stage 3.7.8 reel/retrieve browser probe contract",
    file: "utils/browser-probes/stage_3_batch_007_reel_retrieve_probe_check.js",
    suites: ["quick", "architecture", "tools", "gameplay"],
  },
  {
    id: "stage-3-batch-007-acceptance",
    title: "Stage 3.7.8 superseding acceptance",
    file: "utils/architecture/stage-3-batch-007-acceptance-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-007-release-acceptance",
    title: "Stage 3.7.9 release closure",
    file: "utils/architecture/stage-3-batch-007-release-acceptance-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-008-release-acceptance",
    title: "Stage 3.8.9 exact release closure and browser proof",
    file: "utils/architecture/stage-3-batch-008-release-acceptance-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "stage-3-batch-008-release-fixtures",
    title: "Stage 3.8.9 release transition and strict browser proof fixtures",
    file: "utils/architecture/stage-3-batch-008-release-fixture-check.js",
    suites: ["architecture"],
  },
  {
    id: "stage-3-batch-009-release-acceptance",
    title: "Stage 3.9.9 exact release transition, browser proof and completed prefix",
    file: "utils/architecture/stage-3-batch-009-release-check.js",
    suites: ["quick", "architecture"],
  },
  {
    id: "inventory-v2-transaction",
    title: "Inventory V2 transactions",
    file: "utils/inventory-v2-transaction-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-migration",
    title: "Inventory V2 migrations",
    file: "utils/inventory-v2-migration-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-cast-lure",
    title: "Inventory V2 cast and lure integration",
    file: "utils/inventory-v2-cast-and-lure-check.js",
    suites: ["inventory", "inventory-v2", "gameplay"],
  },
  {
    id: "inventory-v2-line-allocation",
    title: "Inventory V2 line allocation",
    file: "utils/inventory-v2-line-allocation-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "consumable-event-identity",
    title: "Consumable event identity",
    file: "utils/consumable-event-identity-check.js",
    suites: ["inventory", "inventory-v2", "gameplay"],
  },
  {
    id: "inventory-v2-integration",
    title: "Inventory V2 application integration",
    file: "utils/inventory-v2-integration-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "inventory-v2-ui",
    title: "Inventory V2 UI",
    file: "utils/inventory-v2-ui-check.js",
    suites: ["inventory", "inventory-v2"],
  },
  {
    id: "bait-effectiveness",
    title: "Contextual bait effectiveness",
    file: "utils/bait-effectiveness-check.js",
    suites: ["items", "gameplay", "inventory-v2"],
  },
  {
    id: "item-freshness-gameplay",
    title: "Gameplay-backed bait freshness",
    file: "utils/item-freshness-gameplay-check.js",
    suites: ["items", "gameplay", "inventory-v2"],
  },
  {
    id: "hook-domain-semantics",
    title: "Hook domain semantics",
    file: "utils/hook-domain-semantics-check.js",
    suites: ["items", "gameplay"],
  },
  {
    id: "item-stat-contract",
    title: "Final item stat contract",
    file: "utils/item-stat-contract-check.js",
    suites: ["quick", "items", "inventory-v2"],
  },
  {
    id: "fish-rarity",
    title: "Fish rarity",
    file: "utils/fish-rarity-check.js",
    suites: ["items"],
  },
  {
    id: "item-rarity",
    title: "Item rarity",
    file: "utils/item-rarity-check.js",
    suites: ["items"],
  },
  {
    id: "item-rarity-roundtrip",
    title: "Item rarity snapshot and Inventory V2",
    file: "utils/item-rarity-roundtrip-check.js",
    suites: ["quick", "inventory", "inventory-v2", "items"],
  },
  {
    id: "item-progression",
    title: "Item progression",
    file: "utils/item-progression-check.js",
    suites: ["items"],
  },
  {
    id: "item-condition",
    title: "Item condition",
    file: "utils/item-condition-check.js",
    suites: ["items"],
  },
  {
    id: "item-state-hardening",
    title: "Canonical item instance state and persistence",
    file: "utils/item-state-hardening-check.js",
    suites: ["inventory", "inventory-v2", "items"],
  },
  {
    id: "degradation-colors",
    title: "Degradation colors",
    file: "utils/degradation-color-check.js",
    suites: ["items"],
  },
  {
    id: "rarity-production",
    title: "Production rarity configuration",
    file: "utils/rarity-production-check.js",
    suites: ["quick", "items"],
  },
  {
    id: "victory-input",
    title: "Victory input",
    file: "utils/victory-input-check.js",
    suites: ["gameplay"],
  },
  {
    id: "game-cycle",
    title: "Full game cycle",
    file: "utils/game-cycle-check.js",
    suites: ["gameplay"],
  },
  {
    id: "devtools-links",
    title: "DevTools linked parameters",
    file: "utils/dev-tools-linked-parameter-check.js",
    suites: ["tools"],
  },
]);

module.exports = { CHECK_DEFINITIONS };
